### ISSUE TITLE
issue with writing logic to pull value of correct element in array

### ISSUE THREAD

**Issue by adrianshep** [ga-dc/project1#100]
I've written out in pseudocode what I want to happen:  a user starts his flashcards with a first card of index 0 which produces the value of the first element. Every subsequent click on the "next" button adds 1 to the index and produces the value of the next element. 

Here's the latest code I've tried, with several variations before it:

```
$("#next").on("click", function(){
   var i = 0;
          for (i in statesCapitals) {
          $(".qBox").html("What is the state capital of " + statesCapitals[i][0] + "?")
          }
      })
```

I was expecting to see the value of the first element in the array; instead I get the last.

I've been searching for a possible way in online since yesterday afternoon with no joy. I'm feeling like the answer is either embarrasingly simple or a step or two more complicated than what I've been trying.

**Comment by amaseda** [comment]
Hey @adrianshep. Sorry, we were in a meeting -- taking a look at this now!
