### ISSUE TITLE
Pulling from "data-attribute" only allowing me one word

### ISSUE THREAD

**Issue by pdoulatshahi** [ga-dc/project1#101]
```
function newGame(){
    clickCounter = 0;
    output = [];
    clickedTiles = [];
    tileIds = [];
    tilesFlipped = 0;
    food = foodVocab.concat(foodImages);
    shuffleArray(food);
    for(var i = 0; i < food.length; i++) {
        $("#memory_board").append('<div id="tile_'+i+'" data-food='+food[i]+' class="card"></div>');
      }
    $("body").on("click", ".card", function(event){
      clickOnTile(event.target,event.target.getAttribute("data-food"));
    });
  }
```

For the clickOnTile function, I have to have the data-food attribute set to a string w/o spaces, because it only takes up o the first space as an input.

**Comment by jshawl** [comment]
You need double quotes around `'+food[i]+'` inside your for loop.

**Comment by pdoulatshahi** [comment]
Now displaying food[i] for each.

On Tue, Jul 14, 2015 at 11:15 AM, Jesse Shawl notifications@github.com
wrote:

> You need double quotes around '+food[i]+' inside your for loop.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-dc/pbj-project1/issues/101#issuecomment-121279142.

## 

Paul Doulatshahi
(206) 818-5550
