### ISSUE TITLE
Assigning an extra, not-yet-defined class to an html element breaks everything.

### ISSUE THREAD

**Issue by alexbannon** [ga-dc/project1#102]
I have <div class="playerBoxes">, and when I change it to <div class="playerBoxes, playerOne"> it changes everything on my html even though class playerOne is not defined in my style.css page yet. I expected this change to do absolutely nothing yet.

**Comment by alexbannon** [comment]
Nevermind I figured it out you can close this. It's because the first class was relative but the second class was undefined, therefore static, which messed up sub-divs.

**Comment by jshawl** [comment]
:+1:
