### ISSUE TITLE
issue!

### ISSUE THREAD

**Issue by jkoul** [ga-dc/project1#104]
I'm moving forward on the blackjack project and it looks pretty good, but I'm having some trouble assigning values to each card. I think it's an issue of scope in the function I'm using to pull the values.

var cardValues = new Array();
for(i=0; i<cards.length;i++) {
  function getCardValue (i) {
    if(cards[i].rank == '2' || cards[i].rank == '3' || cards[i].rank == '4' || cards[i].rank == '5' ||
    cards[i].rank == '6' || cards[i].rank == '7' || cards[i].rank == '8' || cards[i].rank == '9' || cards[i].rank == '10') {
      value[i] = parseInt(cards[i].rank);
    } else if (cards[i].rank == 'J' || cards[i].rank == 'Q' || cards[i].rank == 'K') {
      value[i] = 10;
    } else if (cards[i].rank == 'A') {
      value[i] = 11;
    };
    return console.log("works???");
  };
}
![screen shot 2015-07-14 at 11 00 07 am](https://cloud.githubusercontent.com/assets/12779671/8676456/8cfe74dc-2a17-11e5-8f22-e647685b082d.png)

![screen shot 2015-07-14 at 9 55 52 am](https://cloud.githubusercontent.com/assets/12779671/8676444/71fcc256-2a17-11e5-9425-977db2ab8c94.png)

Help!

**Comment by jshawl** [comment]
You're defining a function inside a forloop. Can you define that function elsewhere, and call it in the for loop?

**Comment by jkoul** [comment]
Thanks I'll try that. Moved on to creating the "betting/money" section but I'll circle back once that's ready.

**Comment by adambray** [comment]
( @jkoul Feel free to re-open this if you need to followup)

**Comment by jkoul** [comment]
@adambray Ok I was actually just about to ask a follow-up. Will do.
