### ISSUE TITLE
Help with navigating context + scope

### ISSUE THREAD

**Issue by nolds9** [ga-dc/project1#105]
I currently have a question object set up like:
 `{
      text: "Javascript was invented in 1995",
      choices: [true,false],
      answer: true
 }`

I  also have a click listener set up on the choices:

```
$(".choices").children().on("click",function(){
     var response = $(this).html();
      if (response == 'true'){
           console.log("You clicked true")
      } else {
          console.log("you clicked false")
      }
})
```

How can I best compare the response to the answer? Basically replace the hardcoded 'true' in my conditional...

**Comment by nolds9** [comment]
The problem also being that currently I currently both the question object and and event listener, inside a larger event listener's scope...

**Comment by andrewsunglaekim** [comment]
You need to programtically access the object you described in the second line of your issue. Than compare the response to that object's answer

**Comment by nolds9** [comment]
Yep, that was the issue but I started over so I should be fine for now...

**Comment by andrewsunglaekim** [comment]
I'm goign to go ahead and close this issue, reopen or open new issue if you run into any problems!
