### ISSUE TITLE
DOM attribute grab

### ISSUE THREAD

**Issue by Ryan-321** [ga-dc/project1#106]
<div class="pieceContainer">
    <div class="pieceFront"></div>
    <div class="pieceBack" data-id="3"></div>
  </div>

  var flipped = $( ".flip");

  var firstFlip = flipped[0].find("?????????")

Am trying to grab the number from the data-id and then use it to compare to another of the same, but I can't figure out how to grab that number?  not sure if am close, or in a far away galaxy.

**Comment by Ryan-321** [comment]
div class="pieceContainer">
    div class="pieceFront"></div>
    div class="pieceBack"></div>
  /div> 

whited out my html, took out first carrot

**Comment by jshawl** [comment]
`flipped[0]` is a Dom object. use `flipped.eq(0)` to get a jquery object so you can use `.find`

feel free to reopen if this doesn't fix!
