### ISSUE TITLE
having issues with hover event in jquery

### ISSUE THREAD

**Issue by ghost** [ga-dc/project1#109]
i'm trying to get the border of a picture to turn red (from black) when i hover over it, and go back to black when i hover away from it. this isn't related to any of my user stories... just something i thought would be cool to add in. the code i have right now is:

$(".tool").hover(
    function() {
      $(".tool").addClass({"border-color": "#f00"});
    }
    function() {
      $(".tool").addClass({"border-color": "#000"});
    }
  )

i put it before the click event code i wrote for the same class. not only does the hover code not work, but it's disabling my click event as well. hope i provided enough info!

**Comment by jshawl** [comment]
you were super close! you need to add a commae between the two functions, use `css` instead of `addClass` and `border` instead of `border-color` like http://codepen.io/jshawl/pen/MwXEqN

feel free to reopen if you have questions!
