### ISSUE TITLE
array & event listener troubles.

### ISSUE THREAD

**Issue by phantomhaircuts** [ga-dc/project1#111]
- Trying to create a function with an event listener for the scoring of a multiple choice trivia game. 
- Using an array to store the correct answers, and a separate array to store the wrong answers.
- Using a global variable "question" as a counter to determine what index to access in the arrays. 
- Each time an answer is clicked it runs the function 'checkAnswer'

....
The problem I seem to be having is that it is adding the correct answers of each prior round, each time the function is called;
but I only want to check the answer of the current round. 

```
function checkAnswer(){
$(correctIndex[question]).on("click", function(){
  console.log("score!")
    alert("correct!")
    score = score + 1000;
  $("#score").text(score)
  }
)
$(wrongIndex[question]).on("click", function(){
  alert("Wrong!")
  score = score - 1000;
  $("#score").text(score)
    }
  )
}
```

**Comment by andrewsunglaekim** [comment]
if it's accessing the question of the prior round, than i imagine if you set the index to `question + 1` it should work. sounds like an off by one error.

**Comment by phantomhaircuts** [comment]
Correct, question ++ at the end of each round.

but if  the event listener equates to correct in the first round, and wrong in the second...
its will go through the actions of each prior round before performing the correct action.

I've also tried nesting the checkAnswer function in an If Else Statement, but got the same outcome. 

Also tried rewriting it, creating a different function for each round (checkAnswerOne(), checkAnswerTwo(), etc)...

but each work around returns the same thing.

**Comment by phantomhaircuts** [comment]
also tried setting the index to [0] on both correctIndex and wrongIndex, and then performing:
.shift() on both at the end of the function, to delete the first answer...
but it still returns the same thing. 

is there something else I should be looking for or researching?

**Comment by andrewsunglaekim** [comment]
i'm saying inside the where your accessing it. Access `question + 1` instead of just `question` not just incrementing

**Comment by phantomhaircuts** [comment]
Would that mean a separate function for each round?

I think i tried something like that but,
not sure I follow entirely.

**Comment by andrewsunglaekim** [comment]
jsut where you're indexing in the second line of your code `$(correctIndex[question]).on("click", function(){` use `question + 1`

**Comment by andrewsunglaekim** [comment]
but i'm still note entirely sure what the problem is. Could you re articulate the specific concern that you have? What do you expect your code to do vs what is actually happening.

**Comment by phantomhaircuts** [comment]
so the question + 1, seems to work, except it still adds the alerts from the previous rounds.

I think since the function is being called as soon a button is clicked, 
- I expect it to only show the alert corresponding to the current round. *

It seems to act the same regardless of where I'm calling the function, or if I'm nesting the function in an if else statement etc..
but, given my knowledge thus far, I can't seem to determine where the problem lies in my code.

**Comment by andrewsunglaekim** [comment]
i'll swing by in a bit, 30 min~
