### ISSUE TITLE
What is [object, Object]?

### ISSUE THREAD

**Issue by walter-0** [ga-dc/project1#112]
var user = "dude";
var finalScore = 4;

var ranking = function( user, finalScore){
  this.name = user
  this.score = finalScore
}
//high score table
$("#highScore").click(function(){
  var ranking1 = new ranking(user, finalScore)
  alert(ranking1)
  console.log(ranking1);
})

The alert message gives me
 [object, Object] 
but the console log gives me
 Object { name: "dude", score: 4 }

How can I get the alert message to show what the console is showing?

**Comment by jshawl** [comment]
http://codepen.io/jshawl/pen/jPKGRo?editors=101
