### ISSUE TITLE
Listener blocking my transition

### ISSUE THREAD

**Issue by Ryan-321** [ga-dc/project1#114]
$(".pieceContainer" ).on( "click" , function() {
    $( this ).addClass( "flip" );
});

  $(".pieceContainer" ).on( "click" , compareFlipped );

Calling two listeners.  The 2nd listener's call to compareFlipped is blocking the transition I have when I add the class flip in the first listener.  is there a way to delay this or allow the transition to finish?  compareFlipped below if u need

function compareFlipped() {

  var flipped = $( ".flip" );

  if(flipped.length == 2) {
    var flipOne = $( ".flip .pieceBack" ).eq(0).attr("data-id");

```
var flipTwo = $( ".flip .pieceBack" ).eq(1).attr("data-id");

if(flipOne == flipTwo) {
  $( ".flip" ).addClass( "stayFlipped" );
} else if (flipOne != flipTwo ) {
  $( ".pieceContainer" ).removeClass( "flip" );
}
```

  }
}

**Comment by andrewsunglaekim** [comment]
you could activate the event listener for `compareFlipped` after you do `$( this ).addClass( "flip" );`

**Comment by Ryan-321** [comment]
tried it: 
  $(".pieceContainer" ).on( "click" , function() {
    $( this ).addClass( "flip" );
  $(".pieceContainer" ).on( "click" , compareFlipped );
});

and 
  $(".pieceContainer" ).on( "click" , function() {
    $( this ).addClass( "flip" );
    compareFlipped();
});

both had same effect.

**Comment by Ryan-321** [comment]
No worries on this one, got it too work.    used setTimeout
