### ISSUE TITLE
Help with getting the value of a radio button when clicked.

### ISSUE THREAD

**Issue by ghost** [ga-dc/project1#115]
I want to have an alert that says the value of my radio input.

HTML
  <form id="triviaForm">
    <ol>
      <li>Question 1</li>
        <ul>
          <li><input type="radio" name="q1" class="answer" value="correct">A</input></li>
          <li><input type="radio" name="q1" class="answer" value="incorrect">B</input></li>
          <li><input type="radio" name="q1" class="answer" value="incorrect">C</input></li>
          <li><input type="radio" name="q1" class="answer" value="incorrect">D</input></li>
        </ul>

in JS, i tried:
1.  function alertRadioValue() {
        var radioValue = $('input.answer:checked').val();
        alert(radioValue);
     }
1.  function alertRadioValue() {
       var radioValue = $('input[name="q1"]:checked').val();
       alert("radioValue");
    }
2.  $("#triviaForm input").on("click", function() {
       var value = ('input[type="radio"]:checked').val();
       alert(value);
    });

All 3 doesn't work.

**Comment by ghost** [comment]
oops, somehow the HTML code got converted. This is what it's supposed to be:

**Comment by ghost** [comment]
...ok...it's not working..

**Comment by andrewsunglaekim** [comment]
are you invoking those functions at any point?

**Comment by ghost** [comment]
Yeah. If I write alertRadioValue(), I get an alert right away when the page loads. When I put it in a click event, nothing happens when I click on the radio button.
