### ISSUE TITLE
.hide() problem

### ISSUE THREAD

**Issue by chrislovett03** [ga-dc/project1#116]
I want to hide my trivia questions after they've been clicked/answered. Adding a .hide() to the end of a particular block of code doesn't correspond to it's correct cell, depending on which cell I add it too. See screenshots. 

![screen shot 2015-07-14 at 12 50 01 pm](https://cloud.githubusercontent.com/assets/12041606/8679158/fc619f70-2a26-11e5-9433-ab20d8505085.png)
![screen shot 2015-07-14 at 12 50 51 pm](https://cloud.githubusercontent.com/assets/12041606/8679157/fc5f1a20-2a26-11e5-8611-7b4a6f1f53de.png)

**Comment by andrewsunglaekim** [comment]
i'm not sure which html element belongs to `$("#one200")`, but i would throw some console.logs to figure out the different elements

**Comment by chrislovett03** [comment]
![screen shot 2015-07-14 at 1 41 40 pm](https://cloud.githubusercontent.com/assets/12041606/8680257/162853d4-2a2e-11e5-9784-b62e786b5fc8.png)

I've checked all my ID assignments and they are accurate. Any other ideas why this might be happening?
