### ISSUE TITLE
Help with making my code DRY

### ISSUE THREAD

**Issue by skey08** [ga-dc/project1#120]
right now I have this function that is turning one css selector off and turning another one on

```
$("#next.next2").on("click", function(){
  $(".q2.xx").css("display", "none");
  $(".q3.xx").css("display", "block");
})
```

the problem is I have to repeat it 10 times to apply it to each button. Basically I need a function that makes each of those 3 numbers go up by one each time a button is clicked.

**Comment by mattscilipoti** [comment]
I expect you can use a common class, shared across all the relevant elements which can be used by your css selector.

**Comment by skey08** [comment]
I don't want them all off or on at the same time though, as the current one turns off I am turning the next one on:
![screen shot 2015-07-14 at 2 27 02 pm](https://cloud.githubusercontent.com/assets/11445329/8681300/a23100dc-2a34-11e5-8acf-797bdfbd1245.png)

**Comment by jshawl** [comment]
inside your click handler, use `$(this).parent().next()` to reference the next form in your HTML
