### ISSUE TITLE
ReFactoring issue

### ISSUE THREAD

**Issue by MikeDulik** [ga-dc/project1#121]
I am having trouble implementing functions in place of my repetitive code blocks.  My program is functional, but the code is very ugly.  Was just hoping that I could consult with someone on using some functions that I am having trouble building... it would be very constructive for me.  Thanks!

**Comment by amaseda** [comment]
Can you include some example code in here? One of your functions and it's corresponding code block(s).

**Comment by mattscilipoti** [comment]
You could also share a github link to the file in question.

**Comment by MikeDulik** [comment]
var deckLength = cards.length;
var valLength = values.length;
var index = 0;
index = Math.floor((Math.random() \* deckLength) + 1);
// deckInit(deckLength, valLength, index);

function deckInit( dLength, vLength, i){
  var dLength = cards.length;
  var vLength = values.length;
  var i = 0;
  i = Math.floor((Math.random() \* dLength) + 1);
}

https://github.com/MikeDulik/Project1-GA/blob/master/script.js

Adrian, since we are running out of time today with the speaker presenting soon, this would also be a great practice for us to go over together during our 1-on-1 (which I think is this week some time?)... I have hit my MVP so this isn't necessarily urgent, just kind of ridiculous having 500 lines of code when I should probably have under 100 haha
