### ISSUE TITLE
issue with creating incorrect answer function in flash cards app

### ISSUE THREAD

**Issue by adrianshep** [ga-dc/project1#123]
I tried:
$("#incorrect").on("click", function(){
       var incorrect = statesCapitals.splice(i,1);
       statesCapitals.push(incorrect[i]);
       console.log(statesCapitals[4]);
    })

 I expected to see if the array stateCapitals had been altered. Instead, I get 'undefined's on my console. Don't know if I'm trying something too convoluted to work or just got my syntax wrong.

**Comment by mattscilipoti** [comment]
Maybe my translation of the code will help:

``` js
$("#incorrect").on("click", function(){
  // When I click on an incorrect option
  // Remove the the current stateCapital (identified by `i`) and return it as an array
  var incorrect = statesCapitals.splice(i,1);
  // Get the (`i`th) element from `incorrect` (the array that holds the single incorrect item) and add it to  the end of the statesCapitals array.
  statesCapitals.push(incorrect[i]);
  // log the 5th stateCapital to the console.
  console.log(statesCapitals[4]);
})
```

This is what I see happening as I read through your code.  Is that what you expect?

**Comment by adrianshep** [comment]
Correct. The element marked as incorrect should go to the end of the array
(where the user will encounter it again and get another lick at answering
it). Since my current sample array is five elements long, the incorrectly
marked element should be at [4]. The console gives me back undefined,
though.

On Tue, Jul 14, 2015 at 2:55 PM, Matt Scilipoti notifications@github.com
wrote:

> Maybe my translation of the code will help:
> 
> $("#incorrect").on("click", function(){
>   // When I click on an incorrect option
>   // Remove the the current stateCapital (identified by `i`) and return it as an array
>   var incorrect = statesCapitals.splice(i,1);
>   // Get the (`i`th) element from `incorrect` (the array that holds the single incorrect item) and add it to  the end of the statesCapitals array.
>   statesCapitals.push(incorrect[i]);
>   // log the 5th stateCapital to the console.
>   console.log(statesCapitals[4]);
> })
> 
> This is what I see happening as I read through your code. Is that what you
> expect?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-dc/pbj-project1/issues/123#issuecomment-121340614.

## 

Adrian

Адріян Шипилявий

Адь

**Comment by andrewsunglaekim** [comment]
I would `console.log()` waht incorrect and incorrect[i] are.. Additionally log statesCapitals the array and see what you get there. Then you'll know exactly waht you are and aren't getting for each piece of data. I think it will be easier to debug from there.
