### ISSUE TITLE
Help with controlling card side shown, as a default toggle

### ISSUE THREAD

**Issue by petergcutler** [ga-dc/project1#127]
Could use a hint towards creating a way to toggle whether flashcards are displayed on their front side first, by default, or on their back side first.

**Comment by andrewsunglaekim** [comment]
you could just have an event do it. Or on page load/game reset

**Comment by adambray** [comment]
I think too, you'll probably need either a global variable, or, if you're using OOP approach, a property on your game / deck object to store whether you are in front or back mode.

Then, whenever you render a card, use that variable / property to determine which side to render.
