### ISSUE TITLE
understanding logic behind event listener.

### ISSUE THREAD

**Issue by phantomhaircuts** [ga-dc/project1#129]
Talked to Andy about this earlier, made some changes in the function, but still having trouble figuring out what I need to change from here. 

It seems like no matter what I do, its logging more than I anticipate...

function checkAnswer(){
  $(correctIndex[question]).on("click", function right (){
    console.log("score!")
    console.log(correctIndex[question]);
      alert("correct!")
      score = score + 1000;
    $("#score").text(score)
    $(correctIndex[question]).off("click", right);
    })

$(wrongIndex[question]).on("click", function wrong (){
    console.log("wronganswer");
    console.log("wrongIndex[question]")
    alert("Wrong!")
    score = score - 1000;
    $("#score").text(score)
    $(wrongIndex[question]).off("click", wrong);
  })
}

**Comment by jshawl** [comment]
I recommend taking the event listeners outside of your `checkAnswer` function. You should listen for clicks on each button when the dom loads, and then check to see if it's right or wrong.
