### ISSUE TITLE
another scope/context snag

### ISSUE THREAD

**Issue by jkoul** [ga-dc/project1#130]
$("#hit").click(function addPlayerCard(){
  if(playerScore<=21) {
    if ($("div#playerthree").css("visibility") == "hidden") {
      $("div#playerthree").css("visibility", "visible");
      if(playerScore + 11 <=21 && window.cardValues[9]== "A") {
        getValue(window.cardValues[9]) = 11;
      } else {getValue(window.cardValues[9]) = 1;
        };
      playerScore += getValue(window.cardValues[9]);
    } else if 
etc etc...........

the line 
"} else {getValue(window.cardValues[9]) = 1;"
is returning an error of "Uncaught ReferenceError: Invalid left-hand side in assignment"

It was working until I added the if statement flexing the value of an Ace. Is this a scope issue or something else?

**Comment by andrewsunglaekim** [comment]
You're getting that error because you are trying to assign an integer `1` to something that isn't a variable.
