### ISSUE TITLE
Issue persists with hiding tiles after mismatch

### ISSUE THREAD

**Issue by kristingreenslit** [ga-dc/project1#133]
Unable to hide tiles after the two tiles chosen by the user are a mismatch. Tried iterating through the array using a traditional for loop and changing background color, in addition to .forEach(). I am able to change the class for "this" however that will only change the last tile selected by the user vs. the last two tiles selected by the user.

https://github.com/kristingreenslit/GA-Project-1-Game-App/commit/df97f709db9bc8499593eef70239aa0cf66da7da

**Comment by adambray** [comment]
@kristingreenslit sounds like you need to be able to keep track of which tiles need to be flipped back. As you pointed out, just flipping the one that the user clicked isn't enough.

Two thoughts:
1. Could you store the first flipped card's DOM element in a variable (probably needs to be global), and reference that variable later on when you need to flip the card back over.
2. What about appending a class (like `.flipped`) to cards that are flipped over. Once the second card is clicked, just select all elements with the `.flipped` class and do what you need to them.

**Comment by adambray** [comment]
Closing for now, but feel free to re-open if you have followup questions.

**Comment by kristingreenslit** [comment]
Thanks Adam. I've tried both of those but haven't had any success. I agree, they should have worked!

**Comment by adambray** [comment]
@kristingreenslit Can you excerpt the relevant portion(s) of code here that you tried and didn't work?

**Comment by kristingreenslit** [comment]
I'll try. Some of it is prior commits but I've committed everything that I've tried. What's the shortcut again for taking snippets of code?

**Comment by kristingreenslit** [comment]
*some of it is in prior commits but I don't think I've committed everything that I've tried to do to solve the problem

**Comment by kristingreenslit** [comment]
https://github.com/kristingreenslit/GA-Project-1-Game-App/blob/master/script.js#L3-L25

**Comment by kristingreenslit** [comment]
have tried several combinations of assigning "this" to a global variable to fix the issue, but attempts have been unsuccessful. Link to latest commit: https://github.com/kristingreenslit/GA-Project-1-Game-App/blob/master/script.js#L21-L25
