### ISSUE TITLE
checking again on loop

### ISSUE THREAD

**Issue by jkoul** [ga-dc/project1#136]
the line of the for loop below with "#pcards" is yielding the following error:
SyntaxError: missing ) after argument list. I'm not seeing any open parentheses. Help?

var data = {
    one: 7,
    two: 8,
    three: 9,
    four: 10,
    five: 11,
    six: 12,
    seven: 13
  }

  for(key in data) {
    $("#pcards").append("<div class="card" id="'player'+key"></div>");
    $("(div#player)"+key).html(cards[data[key]].createNode());
  };
}

**Comment by jkoul** [comment]
might be the double quotes in the ID & class creators. I'll try fixing that. Can we keep this open for now though?

**Comment by andrewsunglaekim** [comment]
additionally could you wrap sample code in <pre>```</pre>

**Comment by andrewsunglaekim** [comment]
also i think `("(div#player)"+key)` isn't valid jQuery

**Comment by jkoul** [comment]
thanks. i think i'm getting closer now. Here's what i have at the moment.

```
  var data = {
    one: 7,
    two: 8,
    three: 9,
    four: 10,
    five: 11,
    six: 12,
    seven: 13
  }



  for(key in data) {
    var playerCardId = 'player' + key;
    $("#pcards").append("<div id=playerCardId></div>");
    $("div#playerCardId").html(cards[data[key]].createNode()).addClass("card");
  };
```

**Comment by jkoul** [comment]
still struggling here. i may have to go back to the drawing board (or just stick with my somewhat redundant code for now)
