### ISSUE TITLE
chaining selectors with `this`

### ISSUE THREAD

**Issue by mattficke** [ga-dc/project1#137]
I know I can do something like `$(".card .number").text("A")` to select elements of class `number` that are children of an element of class `card`.

Is there a way to use `this` (or `element` when using `each()`)  to select the parent element instead? Something like `$(this ".number").text("A")`

**Comment by andrewsunglaekim** [comment]
`$(this).parent()` if you are iterating through elements in an `each()`

**Comment by andrewsunglaekim** [comment]
but i feel like thats not what you are asking, could you provide more context?

**Comment by mattficke** [comment]
Ah, ok, I see. Got it working with `$(element).children().text("A");`

Which works for what I need right now, though i'm curious if you could do something similar to select some specific subset of the child elements (such as those with class `number`, as per above) rather than all children.

**Comment by andrewsunglaekim** [comment]
Yeah, i think you could use the `.find()` method. Closing issue for now, feel free to reopen or open a new issue if you run into anything.
