### ISSUE TITLE
getElementbyId claims it is null.

### ISSUE THREAD

**Issue by LauraWN** [ga-dc/project1#139]
The console claims that when I try to use document.getElementById("triviaQuestion").innerHTML = triviaData[currentQuestion][0]; that it returns null.

I saw in the MDN that capitalization matters, both in the name "triviaQuestion" and getElementById parts and went through to make sure that triviaQuestion is capitalized that way throughout. Also that getElementById is capitalized like that and not getElementbyID.

**Comment by jshawl** [comment]
try breaking this problem down:

what is the output of `document.getElementById("triviaQuestion")`?

what is the output of `triviaData`

what is the output of `triviaData[currentQuestion]`

what is the output of `triviaData[currentQuestion][0]`
