### ISSUE TITLE
Can't find the URL section of my Github repo

### ISSUE THREAD

**Issue by tomBeach** [ga-dc/project1#140]
My project is on the github server (http://tombeach.github.io/_Project_1) but I can't find the "URL section" on my Project_1 repo page.  The link is visible under Settings / GitHub Pages...  Is that what you are looking for?

**Comment by jshawl** [comment]
just below the name of your project on github, there is a link to edit and input your url

it looks like: 

![](https://dl.dropboxusercontent.com/s/lkjqv7wppzhwl50/url.gif?dl=0)

Closing for now but please reopen if you have issues
