### ISSUE TITLE
I need help with my css styling and JS function

### ISSUE THREAD

**Issue by Thesheik** [ga-dc/project1#143]
I am trying to get my divs to align side by side but I am have trouble doing so.
Also I need help with my game functionality

**Comment by jshawl** [comment]
can you please provide what you've tried, what code you wrote and what problem you're running into explicitly?

**Comment by Thesheik** [comment]
Here's my css code:
box{
  border:0.5px solid black;
  margin: 15px;
  width: 600PX;
  height: 300px;
  text-align:center;
  line-height: 300px;
  background-color: beige; color: black;
  display: inline-block;
}

header{
  text-align: center;
  font-family:black;
  background: black;color: white
}

.flashcards {
  border: 1px solid black;
  margin: 10px;
  width: 200px;
  height: 200px;
  text-align: center;
  background-color: re;
  display:inline-block;
}
And as far my javascript goes I just need some help figuring out how to when toggle onclick on a slide, the slide can vanish.
