### ISSUE TITLE
Git pushing new branch to overwrite master

### ISSUE THREAD

**Issue by M00staff** [ga-dc/project1#144]
I want to completely overwrite my master with a new branch - i do not want to merge them.

Would i just 'git push origin master' while working in the branch i want to replace it with?

**Comment by andrewsunglaekim** [comment]
that will just push the changes on your branch to the master, which is essentially is the same as merging first then pushing, why do you not want to merge?

**Comment by M00staff** [comment]
I'm worried it might mess something up

**Comment by M00staff** [comment]
plus I'm running a little short on time

**Comment by M00staff** [comment]
ok so i was overthinking it - the merging worked fine. 

Worth noting that i changed repo's Monday.  So the one i turned in over the weekend is not the same one i am using now.  I didn't realize we were supposed to put it in the username.github.io repo originally. 

Does that make sense?  Not sure if it matters.

**Comment by mattscilipoti** [comment]
You should have a repo specifically for this project.  username.github.io is for your personal branding webpage, not this project.
