### ISSUE TITLE
Github pages

### ISSUE THREAD

**Issue by malissaromero** [ga-dc/project1#147]
Hello,

I followed the instructions from github pages to create my page before I saw the online instructions. I git pulled from my terminal to make sure to get the gh_pages on my local terminal and it says that it is up to date but I do not see the gh_pages branch on my local terminal. 

Thank you.

**Comment by jshawl** [comment]
what is the output of `git branch -a` ?

**Comment by malissaromero** [comment]
remotes/origin/HEAD -> origin/master
  remotes/origin/gh-pages
  remotes/origin/gh_pages
  remotes/origin/master

I added the gh_pages from github before the instructions were posted.

**Comment by malissaromero** [comment]
I deleted the gh_pages from github and created the gh-pages branch. I am trying to do the git push --set-upstream but an error message now returns:

 ! [rejected]        gh-pages -> gh-pages (fetch first)
error: failed to push some refs to 'git@github.com:malissaromero/The-Office-Trivia-Game.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

I am afraid to git pull because I don't want to lose all my changes.
