### ISSUE TITLE
Issue with pushing objects into array

### ISSUE THREAD

**Issue by tomiteo** [ga-dc/project1#158]
I'm working on the JS underpinning War, and I'm encountering unexpected behavior:

```
var card = {
  value : null,
  suit : null,
};

var createCard = function(value){
  var newCard=card;
  newCard.value=value;
  return newCard;
};

var createDeck = function(){
  var newDeck=[];
  console.log(newDeck);
  for (var i = 2; i <= 14; i++) {
    var newCard = createCard(i);
    console.log(newCard);
    newDeck.push(newCard);
    console.log(newDeck);
  }
};

createDeck();
```

I expected createDeck() to create an array of objects, each with its own value property of 2-14, but instead the console displayed an array of objects, all with value 14

**Comment by jsm13** [comment]
Short answer is that there is only one card. The original card declared. Every assignment has passed a reference to that same first card. You'll want to fix this by creating the card within createCard

**Comment by RobertAKARobin** [comment]
Gahh, John beat me! I'm answering anyway.

Ooh, interesting! This is a little weird. Whenever you say `var newCard = card`, Javascript _doesn't_ create a copy of `card`, it just uses the same old card. If you want to create a whole new card, you'll need to do something like:

``` js
var createCard = function(value){
  var newCard = {
    value: null,
    suit; null
  };
  newCard.value=value;
  return newCard;
};
```

**Comment by tomiteo** [comment]
wow! it's working now! thanks guys!

**Comment by tomiteo** [comment]
so my understanding is that each index of the array was at first just referencing the same one card over and over again, but now with `var newCard = {
    value: null,
    suit: null
  };`
it's creating a new object each time

**Comment by RobertAKARobin** [comment]
Yup!

**Comment by jsm13** [comment]
Bit on mutability and referencing objects in [eloquent js](http://eloquentjavascript.net/04_data.html#h_C3n45IkMhg)
