### ISSUE TITLE
Can't verify

### ISSUE THREAD

**Issue by clarktsc39** [ga-dc/project1#159]
When I try to verify my gh page, it's not showing up

I type this into my browser: `<clark-thomas>.github.io/<project1>`

And there's a 404 error

**Comment by RobertAKARobin** [comment]
Remove the angle brackets `<>`. The link should be `clark-thomas.github.io/project1`.

That said, the link still isn't working. I'ma inspect this.

**Comment by clarktsc39** [comment]
I tried that too. Still no luck...

**Comment by RobertAKARobin** [comment]
It's working:

http://clark-thomas.github.io/project1/readme.md

You just can't see anything because Github looks for a file called `index.html` so show as the default file. If it can't find that, it doesn't know what to show, so it 404s.

The solution is to just create an `index.html`.

**Comment by clarktsc39** [comment]
ok, thanks

**Comment by clarktsc39** [comment]
Ok, thanks
