### ISSUE TITLE
issue with selecting elements

### ISSUE THREAD

**Issue by ghost** [ga-dc/project1#161]
Trying to select a particular element by class to change its background from white to red.  class='card' is child of class='rowOne'.

I tried 

``` js
$('rowOne.card').eq(1).css('class', 'red')
```

I expected the background attribute in .color to change.

Instead, console returns an empty array [].

**Comment by RobertAKARobin** [comment]
`rowOne.card` means "an element called rowOne with a class of card". That is:

```
<rowOne class="card"></rowOne>
```

**Comment by jsm13** [comment]
MDN's [guide to selectors](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Getting_started/Selectors) is really good

**Comment by ghost** [comment]
Helpful, think I'm making progress.

```
$('div.rowOne .card:eq(3)').css('background', 'red')
```

This seems an intermediate step for me but at least helps me understand how to get where I want to be.

**Comment by RobertAKARobin** [comment]
Cool! I haven't seen `:eq` before.
