### ISSUE TITLE
Basic Issue

### ISSUE THREAD

**Issue by dan-ator** [ga-dc/project1#162]
I am trying to set up an object array with data for my flashcards and a function to call the front of the flashcard, with another to call the back.  It is basic so far and I am not sure this will work for the flashcards anyways, but I am having some errors I did not expect.

``` js
$(document).ready(function() {

  var cardData = {
    number: "4",
    word: "hello",
    color: "red"
  };

  function cardFront(cardData) {
    for (var i = 1 ; i < cardData.length ; i++) {
    console.log(cardData.name);
  }
  };

  function cardBack(cardData) {
    console.log("frog");

  };
});
```

When I open it in the console in my browser though it says that cardBack and cardFront are undefined and when I try just inserting the calling of the cardFront function into the code, it tells me it ''cannot read length of undefined''.

**Comment by andrewsunglaekim** [comment]
In your for loop, you're trying to call the length method. If the argument that you pass in the function invocation is undefined, you'll get an error saying that.  Can you show in your code where you're invoking the functions?

**Comment by dan-ator** [comment]
I tried invoking the function in the console in Chrome.  Here I was just trying to declare the functions for later use.

**Comment by andrewsunglaekim** [comment]
it's not defined in the global name space. Its defined in your `$(document).ready`. So you won't have access to that function in the console in the browser.

**Comment by dan-ator** [comment]
I tried removing the $(document).ready and all its brackets but I get the same error for cardFront() when I try to invoke it in the console.

**Comment by andrewsunglaekim** [comment]
what are you passing in as an argument to `cardFront()`?

**Comment by andrewsunglaekim** [comment]
The way you've written it, it requires an argument. It doesn't automatically pass in the object you created in the above lines.

**Comment by andrewsunglaekim** [comment]
Would need to look something like 

``` js
 var cardData = {
    number: "4",
    word: "hello",
    color: "red"
  };

  function cardFront(arg) {
    for (var i = 1 ; i < arg.length ; i++) {
    console.log(arg.name);
    }
  };

cardFront(cardData);
```

**Comment by dan-ator** [comment]
Ahh.  Ok now I passed cardData into it and it gave me undefined, rather than an error.  Which I suppose is better?  

I want the object attributes in my var cardData to be put out by the cardFront function.

**Comment by andrewsunglaekim** [comment]
can't call length on an object, only arrays. So when you pass cardData into it, eventually in your for loop, it'll run `cardData.length` which is undefined. Try doing `Object.keys(cardData)` to get all of the keys in the object, than finding its values with those.

**Comment by dan-ator** [comment]
you mean `object.keys(cardData)` goes in the for loop or somewhere else?

**Comment by nolds9** [comment]
In your cardFront function: I might recommend a different kind of iteration, maybe a for...in loop (to access values of keys in the object) [MDN reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in)

 Or use the method andy recommended to make an array that you would iterate over.

**Comment by dan-ator** [comment]
@andrewsunglaekim I don't understand the method you are suggesting.  Do I just substitute `object.keys(cardData)` in somewhere or is that instead of a for loop?

**Comment by dan-ator** [comment]
I am still having an issue.  I have the following code:
`
cardData = [
    {front: "gracias", back: "thank you"},
    {front: "hola", back: "hello"},
    {front: "zapato", back: "shoe"},
    {front: "camisa", back: "shirt"}
  ];

  function cardFront(cardData) {
    for (var i = 1 ; i < cardData.length ; i++) {
    console.log(cardData[i]);
  }
  }

  function cardBack(cardData) {
    console.log("frog");
  }

  cardFront();
`

and it is still telling me it cannot read property length of undefined.  But I thought since it is now an array it would work for that?

**Comment by nolds9** [comment]
When you call cardFront() at the end, you need to pass something in as an argument because your definition requires an argument.
for example: 

``` js
function cardFront(cardData) {
  for (var i = 0 ; i < cardData.length ; i++) {
    console.log(cardData[i]);
  }
}
```

cardData referenced above is actually only a placeholder for the data you will pass in when you call that function.
