### ISSUE TITLE
Issue with storing variables into separate clicks for Memory game

### ISSUE THREAD

**Issue by Ly900** [ga-dc/project1#163]
I am trying to store the image source of each click into a variable in order to compare them later. I expected each click to store into a different variable. Instead, each click stored into both variables which end up being the same. 

I tried calling the clicks from different functions but since they execute immediately after, that did not work either.

Below is what I have so far for the code:  

``` js
$("img").hide();

function findMatch () {
  var image1;
  $("td").click(function () {
    image1 = $(this).find("img").show().attr("src");
    console.log(image1);
    $(this).off();
  });

  var image2;
  $("td").click(function () {
    image2 = $(this).find("img").show().attr("src");
    console.log(image2);
    $(this).off();
  });

};
```

**Comment by RobertAKARobin** [comment]
Sorry for the delay, Ly. So the problem is `image1` and `image2` are the same, when they should be different?

Also, both of these click functions look pretty much identical. Is there some way this could be DRYed up by both `td`s using the same click function?

**Comment by RobertAKARobin** [comment]
Looking at this again, I think the problem is that you're doing `$("td").click` twice. jQuery doesn't know which `<td>` you mean, and I'm guessing you have several of them. If you want `$("td").click` to just affect the **very first** `<td>`, you'd need to be specific about the "very first" part. For instance:

``` js
$("td").eq(1).click(function(){
// ...
})
```

**Comment by Ly900** [comment]
Robin, here is the new code with only one click event. I tried to use a while loop so that it only pushes while clickedCard.length < 2 but it gives a loop that doesn't end.

``` js
$("img").hide();
var clickedCards = [];
var clickCounter = 0;

function findMatch () {
  while (clickedCards.length < 2) {
    $("td").click(function () {
      image = $(this).find("img").show().attr("src");
      clickedCards.push(image);
      clickCounter++;
    })
  }
} 
```

**Comment by RobertAKARobin** [comment]
I believe that's because it only calculates `clickedCards.length` once, when the `while` loop is first run. It doesn't re-calculate it each time. So the while loop will continue forever. Instead, try something like this:

``` js
var numberOfCards = 0;
while(numberOfCards < 2){
  numberOfCards++;
  // everything else here
}
```
