### ISSUE TITLE
Trivia - Trouble getting array of questions to display

### ISSUE THREAD

**Issue by ArmaniH** [ga-dc/project1#167]
For the trivia, I'm trying to get a question from my array to appear on screen when the user clicks to begin. The click event is working to display text, but I can't figure out how to get one of the questions to appear instead of just some placeholder text in `<p>`.

My array

``` js
var triviaQuestions = {
  Question1: ['How tall am I?'],
  Question2: ['How old am I?'],

My function
$( ".start" ).click(function() {
      $('p').replaceWith($('id', triviaQuestions[0]));
      $('p').show('slow');
      $('h2').show('slow');
      })
```

My HTML for <p>

```
<p style='display: none' class='questions'>This is a trivia question</p>
```

**Comment by RobertAKARobin** [comment]
I'm sorry for the delay in responding, Armani! I'm checking it out now.

**Comment by RobertAKARobin** [comment]
Can you tell me what's going on here:

``` js
$('p').replaceWith($('id', triviaQuestions[0]));
```

A `$` should only go around a CSS selector, and `'id', triviaQuestions[0]` doesn't look like a selector!

**Comment by ArmaniH** [comment]
That $ defintiely wasn't helping me out. Removed!

Still not pulling from the array and when I tried to console.log the '.' in console.log is causing an error.

**Comment by RobertAKARobin** [comment]
Wat. Can you show me the text of the error, and the line that contains the problematic console log?

**Comment by ArmaniH** [comment]
![screen shot 2015-10-26 at 5 24 50 pm](https://cloud.githubusercontent.com/assets/13981641/10742983/9cf74af8-7c06-11e5-9434-bc840bc87627.png)

**Comment by RobertAKARobin** [comment]
That's because you put a `csonole.log` inside your object, and you can't really do that. You have to put it outside the object. It's similar to how this wouldn't work:

``` js
"My name is " + console.log("hello") + "Joe."
```

**Comment by ArmaniH** [comment]
That makes perfect sense!

The triviaQuestions array is coming back as undefined

**Comment by RobertAKARobin** [comment]
Can you copy and paste from where you set `triviaQuestions` to the `console.log`?

**Comment by ArmaniH** [comment]
![screen shot 2015-10-26 at 5 38 51 pm](https://cloud.githubusercontent.com/assets/13981641/10743279/7a4b8d1e-7c08-11e5-9ce1-1df1b27b561a.png)

**Comment by RobertAKARobin** [comment]
You're trying to `console.log` nothing! Put something in those parentheses. :)
