### ISSUE TITLE
Trivia issue

### ISSUE THREAD

**Issue by starrchen** [ga-dc/project1#170]
I am trying to have my trivia game work with different answer choices (A vs. B vs. C) being possible correct choices AND to have the score increase with each correct answer choice only. (So far, have only been able to do this when the correct answer was always A.)

I expected this sequence of steps:
- Choose the correct answer for question 1
- Score increases
- Click "next"
- Choose correct answer for question 2
- Notified that answer is correct. Score increases
- Etc.

What happens instead is:
- Choose correct answer for question 1
- Score increases
- Click "next"
- Choose correct answer for question 2
- Notified that answer is correct. Score does NOT increase unless it is the same div (A vs. B vs. C) as the first correct answer

I talked with Adrian about this during our one-on-one and he said it was something about the event listener still being attached to the div that was correct for question 1 but I'm still not quite sure how to fix this.

Current iteration of my code should be on my project repo page: https://github.com/starrchen/Project-1

Thanks!

**Comment by RobertAKARobin** [comment]
Adrian should be coming over. If he misses you, just reply to this!
