### ISSUE TITLE
Quick question on for/if

### ISSUE THREAD

**Issue by dan-ator** [ga-dc/project1#171]
In an if/else statement, how do I tell it to just do nothing in the else part?  In other words, 

```
function nextButton() {
    if (currentNumber < (cardData.length-1)) {
      currentNumber++;
      drawCard();
    } else {
      alert("You're Done!")
    }
  }
```

instead of using the alert to say youre done, I want it just not to do anything.

**Comment by RobertAKARobin** [comment]
Three backtics for multiple lines of code!

Just omit the `else` bit:

``` js
function nextButton() {
    if (currentNumber < (cardData.length-1)) {
      currentNumber++;
      drawCard();
    }
  }
```
