### ISSUE TITLE
Conceptual Animation Issue/Quesiton

### ISSUE THREAD

**Issue by tylercrosse** [ga-dc/project1#175]
I don't have any specific error. I'm trying to figure out the best way to animate my flash card game. I have it set up so that there are 7 visible cards that are generated from an object. These cards are contained in static divs i.e. card-slots. The user can cycle through these cards, which removes the contents of the card-slots at either end of the visible cards, and generates new cards into the card-slot from the deck to replace them.

```
[card1slot] [card2slot] [card3slot] [card4slot] [card5slot] [card6slot] [card7slot]
```

Cards are cycled by cutting&pasting the contents of each card-slot to the next one in a sequence that starts by removing the contents on the end. This leaves an empty card-slot which is filled by generating a new card from the deck.

I'm trying to figure out the best way to animate these transitions but I'm not really sure where to start.
-maybe instead of cutting&pasting the contents of the static card-slots into the adjacent card-slot I could add an a class containing an animation?

**Comment by RobertAKARobin** [comment]
Adding a class containing an animation is probably your best bet!

An animation is a series of "frames". You define a CSS animation using "keyframes", which are the main "states" your animation needs to occupy at some point. For instance, if you want to have an animation of a box moving 200px to the right, you would have two keyframes: the first is the box in its starting position, the second is the box 200px to the right. The browser automatically fills in the frames between those keyframes in a process called "tweening".

So think about what the "keyframes" are that you need here. You might want to start off with jQuery's built-in `slideUp`, `slideDown`, `fadeOut`, and `fadeIn` methods, just to get a feel for things.

**Comment by RobertAKARobin** [comment]
If you really want to do CSS animations, then I'd start off by creating a little scratchpad `index.html` file and just playing with animations on there to get a feel for them. They can be a little weird. We won't get into animations until later on in the class, but if you want to get a jumpstart you might take a look at this: https://github.com/ga-dc/dolphin-cat-css-animations

**Comment by tylercrosse** [comment]
When I was trying to figure out more about animations I went ahead and did that. I've got ~200 lines of CSS that animate the transitions. I guess the issue I'm running into is that when a card-slot is animated to move to the next location it will abruptly change names when the contents are cut&paste to the new div.

Here is an example of some of the animations I've written:

```
.currentAnimate {
  animation: currentRight 1.6s cubic-bezier(0.86, 0, 0.07, 1) infinite alternate;
  animation-delay: 0;
  animation-fill-mode: none;
  animation-play-state: running;
}

@keyframes currentRight {
  0% {
    background-color: blue;
    z-index: 4;
  }
  100% {
    transform: scale(0.8125) translateX(145px);
    background-color: rgb(0, 36, 144);
    z-index: 3;
  }
}
```

**Comment by RobertAKARobin** [comment]
Wow! 200 lines!

I'm afraid none of us are pro animators, so you're on your own for this one! Just keep trying things. Make sure, though, that the rest of your app works before you let CSS take over your life!

**Comment by tylercrosse** [comment]
Haha, the basic program functions are ok. But the CSS is definitely starting to take control. I'll keep working on it and hopefully I can figure it out, thanks.
https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTUxJxljYyOv1VStMttDHB-Zwrbo9FVbtDCngtYDG4eqdRz3tmV

**Comment by RobertAKARobin** [comment]
Hah, that's a great image!
