### ISSUE TITLE
Empty Divs Not Showing up

### ISSUE THREAD

**Issue by clarktsc39** [ga-dc/project1#176]
I have html that looks like this: 

``` html
<div class="FlashCard"></div>
<div class="FlashCard"></div>
```

I have CSS that looks like this:

``` css
.flashCard{
  border-width: 25px;
  float: right;
  min-height: 1px;
  padding: 100px;
```

The divs aren't show up when I load my index.html...

**Comment by RobertAKARobin** [comment]
That's because classes are case-sensitive. You have `FlashCard` in your HTML and `flashCard` in your CSS.

**Comment by clarktsc39** [comment]
You're a genius! Thank you!

**Comment by RobertAKARobin** [comment]
Just an instructor. :)
