### ISSUE TITLE
issue with merging branches

### ISSUE THREAD

**Issue by ghost** [ga-dc/project1#179]
I want to confirm my planned steps before I merge a branch to master.

I created Branch_A and have solved a few problems in it.  This branch contains the latest progress on the project.  Work is committed to that branch.  

To merge this back to master, I should first merge master to Branch_A, then merge Branch_A to master.  That will ensure master is the latest version of my project, correct?

**Comment by RobertAKARobin** [comment]
That's correct!

**Comment by ghost** [comment]
thanks!
