### ISSUE TITLE
issue with variables

### ISSUE THREAD

**Issue by tkentor** [ga-dc/project1#182]
I tried to display a message in my console after a certain button was clicked five times. The message displayed immediately instead.

```
  var questions = ["", "question1", "question2", "question3" ];
  var currentQuestion = 0;
  var nextQuestion = function ( event ) {
    $("h2").text(questions[currentQuestion]);
    currentQuestion += 1;
  };

  if (currentQuestion = 4) {
    console.log("A message")
  };

$("input").on("click", nextQuestion); 
```

**Comment by RobertAKARobin** [comment]
You're short one equals sign here:

``` js
if (currentQuestion = 4) {
```

**Comment by tkentor** [comment]
Hm okay, now it doesn't display the message at all though, even if currentQuestion == 4.

**Comment by RobertAKARobin** [comment]
Also, your `if` statement isn't actually inside the `nextQuestion` function.

**Comment by tkentor** [comment]
Thanks!
