### ISSUE TITLE
Keydown event listener

### ISSUE THREAD

**Issue by starrchen** [ga-dc/project1#184]
I am trying to have my div.next pass a function on mouseclick and on keydown of the enter key when the div is visible. (It is hidden until an answer is chosen.)

Right now, it works on mouseclick, but the keydown function still proceeds to the next question even when the div is hidden.

``` javascript
var onNext = function(){
  questionCount++;
  addQuestion();
  addAnswers();
  $(".right-or-wrong").hide();
  $(".next").hide();
  $(".answer").css("color", "black");
  clickCount = 0;
  chooseAnswer();

// for the last question, next box changes to a "game over" box
  if (questionCount >= (triviaPrompts.length - 1)) {
    $(".next").on("click", function(){
      window.open("https://www.youtube.com/v/v4IC7qaNr7I&autoplay=1", "_blank");
    });
      // $(".next").html("<a href='https://www.youtube.com/v/v4IC7qaNr7I&autoplay=1' target='_blank'>" + "Game over! " + " <p class = 'fa fa-play-circle'></p>" + "</a>");
    }
};

$(".next").on("click", onNext);
$("html").on("keydown", function(e){
  if ($(".next").css("style") !== "display:none"){
    if (e.keyCode == 13) {
      onNext();
      console.log("enter");
    }
  }
});
```

I'm also struggling to get that div to open a window when it changes to game over. Not sure why it's not working. :(

**Comment by starrchen** [comment]
I'm also struggling to get that div to open a window when it changes to game over. Not sure why it's not working. :(

**Comment by RobertAKARobin** [comment]
There are a couple things that stand out to me here. One is this:

``` js
  if (questionCount >= (triviaPrompts.length - 1)) {
    $(".next").on("click", function(){
      window.open("https://www.youtube.com/v/v4IC7qaNr7I&autoplay=1", "_blank");
    });
  }
```

Usually, you don't want to have an event listener inside an `if/else` statement -- it's the other way around. Try this:

``` js
$(".next").on("click", function(){
  if (questionCount >= (triviaPrompts.length - 1)) {
    window.open("https://www.youtube.com/v/v4IC7qaNr7I&autoplay=1", "_blank");
  }
});
```

The other thing is this:

``` js
if ($(".next").css("style") !== "display:none"){
```

That's telling the browser, "Get the CSS property called 'style'." There isn't a `style` property. Remember, properties are things like `color` and `background` and `margin`.

Instead, you want this:

``` js
if ($(".next").css("display") !== "none"){
```

...but keep in mind that if you have multiple elements with the class of "next" this may not work, since `$(".next")` gets **all** elements with the class of "next".

**Comment by starrchen** [comment]
@RobertAKARobin I tried these out and my next div is still not opening the URL when I click on it. :disappointed:  I tried putting in a console.log in that event listener to see what's going on, but I'm more confused now because it seems to be trying to add a new question (even though we are at the last question) rather than opening the URL. Is it that that event listener gets overridden by the one I put on the div right afterwards?

**Comment by RobertAKARobin** [comment]
Can you show me what your code looks like now? Also, are you getting any errors?

**Comment by starrchen** [comment]
@RobertAKARobin Sure, here's my code right now. 

``` javascript
var onNext = function(){
  questionCount++;
  addQuestion();
  addAnswers();
  $(".right-or-wrong").hide();
  $(".next").hide();
  $(".answer").css("color", "black");
  clickCount = 0;
  chooseAnswer();

// for the last question, next box changes to a "game over" box
  if ( questionCount >= (triviaPrompts.length - 1) ) {
      $(".next").html("Game over! " + " <p class = 'fa fa-play-circle'></p>");
    }

  $(".next").on("click", function(){
    if ( questionCount >= (triviaPrompts.length - 1) ){
      console.log("game over!");
      window.open("https://www.youtube.com/v/v4IC7qaNr7I&autoplay=1", "_blank");
    };
  });
};

$(".next").on("click", onNext);
$("html").on("keydown", function(e){
  if ($(".next").css("display") !== "none"){
    if (e.keyCode == 13) {
      onNext();
      console.log("enter");
    }
  }
});
```

When I click on the "game over" box, I get `TypeError: triviaPrompts[questionCount] is undefined`, so it seems like it's still trying to add a question (from earlier in the code). I think this is just because it is still trying to do the function `addQuestion()`, but is this event listener overriding the one to open the URL?

**Comment by RobertAKARobin** [comment]
Hmm. Where are you calling `triviaPrompts[questionCount]`? I'm not seeing that in your code anywhere.

**Comment by starrchen** [comment]
@RobertAKARobin 
The function `addQuestion()` does:

``` javascript
var addQuestion = function() {
  $(".question").text(triviaPrompts[questionCount][0]);
};
```

**Comment by starrchen** [comment]
@RobertAKARobin Would it be easier for me to attach/us to just go over the whole thing, since my next div is currently calling so many functions?

**Comment by RobertAKARobin** [comment]
I think that's the problem. `triviaPrompts[questionCount]` implies that there's a `triviaPrompts` object with a `questionCount` property. That is, something like this:

``` js
var triviaPrompts = {
  questionCount = 0
}
```

It looks like that's not in your code anywhere...?

**Comment by starrchen** [comment]
`triviaprompts` is an array and I use `questionCount` to call indices in that array.

**Comment by RobertAKARobin** [comment]
Yeah, I'll come find you

**Comment by starrchen** [comment]
@RobertAKARobin Thanks so much! I'm in classroom 1.

**Comment by starrchen** [comment]
@RobertAKARobin So now it's giving me that same error about `triviaPrompts[questionCount]` being undefined after I click next once after the first question, and then I don't see the error ever again, it seems. (This is after I un-commented my other questions.)

**Comment by RobertAKARobin** [comment]
Huh. Are you SURE that's the only thing you changed? I can think of literally no way that adding more questions would have broken it.

**Comment by starrchen** [comment]
Pretty sure that was the only thing I changed. I don't know why I get the error ONLY after the time I click "next", and then it isn't an issue afterwards?

**Comment by RobertAKARobin** [comment]
Is everything actually working, aside from the error?

**Comment by RobertAKARobin** [comment]
The thing to check is what `questionCount` is after each click.

**Comment by starrchen** [comment]
I think you're right as far as what `questionCount` is, because now my points are off and I think I'm missing questions. Now it's skipping my 2nd and 3rd questions, and my questionCount is off by 2, which is shown when my end point value max is 80 points instead of 100.

**Comment by starrchen** [comment]
OHMYGITHUB I was missing a comma. Let me see if it's working now.

**Comment by RobertAKARobin** [comment]
Wat. I'm in a meeting at the moment. Can you push all your code to Github, and I'll take a look?
