### ISSUE TITLE
git fatal error

### ISSUE THREAD

**Issue by jenpen** [ga-dc/project1#193]
I'm receiving the following error: 

---

fatal: Unable to create [myDirectory].git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.

---

Other than git status and git branch, I'm not able to run many git commands including git add, git commit, or git checkout. Online resources provide a range of solutions and the most popular is to delete the index.lock file file the .git directory. I wanted to check with someone before executing on this though. 

Thanks!

**Comment by RobertAKARobin** [comment]
Yup, go with the resource you found! `rm .git/index.lock`.
