### ISSUE TITLE
changing image source or background image url

### ISSUE THREAD

**Issue by onesick** [ga-dc/project1#194]
I tried to change the url or source of image by doing the following;

``` js
    var playerTwoCard=setUp.playerTwoHand.pop();
    var twoURL="cards-svg/"+playerTwoCard+".svg";
    $('#player2_hand').css({
      'background-image': 'url(twoURL)',
      'background-size': 'contain'
    });
```

However, everytime inside of 'url(twoURL)' is read as a string and does not recognize the var. Is there any way that I can achieve this without manually creating an objects or classes with the urls on css and recall thoese preloaded ones?

Thank you

**Comment by RobertAKARobin** [comment]
That's because `url(twoURL)` is inside quotes. Anything inside quotes is treated as a piece of _text_, not as a piece of _code_.

Try this:

``` js
'background-image': 'url(' + twoURL + ')',
```
