### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by clarktsc39** [ga-dc/project1#197]
My console it stating there's an error in my code in the 'else' statement. I figured out how to make the answer hide on the first card, but when I change cards with the "next card" button, it shows all the answers from there on out...

I added the else statement so that I could down press another key and it would hide the answers again.

```
$("body").on("keydown", function(evt){
console.log(evt.keyCode);
if (evt.keyCode == 32) {
  $(".answer").show();
  else (evt.keyCode != 32) {
  $(".answer").hide();
})
})
```

**Comment by amaseda** [comment]
Looks like you forgot to close your `if` statement with a `}`. Does that fix it?

Also, `else` doesn't need a conditional. It acts as a default case that runs if your `if` or `else if` statements are not triggered.

**Comment by clarktsc39** [comment]
For some reason when I add another closing }, it show a button that I had hidden.

**Comment by clarktsc39** [comment]
Now nothing is showing up in the flash cards.

**Comment by amaseda** [comment]
Are any errors showing up in the console now?

Could things hiding/showing be because your if-else statement is working now?

**Comment by clarktsc39** [comment]
``` js
$(document).ready(function() {
  var questions = ["What are the two basic types of investing?", "Who's the most famous value investor?", "What's the difference between market price and value?"]
$(".question").html(questions[0])

  var answers = ["Technical and Fundemental", "Warren Buffett", "Analysis."]
  $(".answer").html(answers[0])

  var questionPosition = 0
  $(".button").click(function() {
    $(".question").html(questions[questionPosition])
    questionPosition++;
  });

  var answerPosition = 0
    $(".answer").hide();
  $(".button").click(function() {
    $(".answer").html(answers[answerPosition])
    answerPosition++;
  });


$("body").on("keydown", function(evt){
console.log(evt.keyCode);
if (evt.keyCode == 32) {
  console.log("keypressed");
  $(".answer").show();
if (evt.keyCode == 80) {
  $(".answer").hide();
```

});

```
});
});
```

**Comment by clarktsc39** [comment]
I'm now getting an error on that }); that I singled out.

**Comment by clarktsc39** [comment]
And when I delete it, the error just moves to the next closing bracket.

**Comment by RobertAKARobin** [comment]
Do you have backtics in your code?

**Comment by clarktsc39** [comment]
Not that I see.

**Comment by clarktsc39** [comment]
I just looked over everything again.

**Comment by RobertAKARobin** [comment]
Oh. You're missing some curly braces:

``` js
if (evt.keyCode == 32) {
  console.log("keypressed");
  $(".answer").show();
if (evt.keyCode == 80) {
  $(".answer").hide();
```

Should be:

``` js
if (evt.keyCode == 32) {
  console.log("keypressed");
  $(".answer").show();
}
if (evt.keyCode == 80) {
  $(".answer").hide();
}
```

**Comment by clarktsc39** [comment]
Sweet, it's working!!!!
