### ISSUE TITLE
file not being located at jquery

### ISSUE THREAD

**Issue by onesick** [ga-dc/project1#199]
```
GET file:///Users/wonsikjeong/wdi/exercises/project1/cards-svg/1D.svg net::ERR_FILE_NOT_FOUND
```

the following message was generated in jequery.min.js line 3.
I am not sure why it's happening, majority of svgs are found but there are some cards won't be located.

**Comment by RobertAKARobin** [comment]
Huh. Well, that file just doesn't exist for some reason. Maybe it's in a different folder?

**Comment by onesick** [comment]
when I got the svg files, those drawing cards like ace and jacks were name like AD for ace dia. And I changed the names to the number values like 1D corresponds to my codes. I think for svg files I can't just rename them.. there must be some hidden codes embeded whtin the files dictating the file name. one way to solve the problem is to change my code to corresponds to it. But I would like to take this as the last step when I do not know what else to do anymore. I want to be able to manipulate the given resources on my codes. Do you think I can do this in coding?

**Comment by RobertAKARobin** [comment]
Nah, you can totally rename them. Try this: copy and paste the link you're trying to use (`file:///Users/wonsikjeong/wdi/exercises/project1/cards-svg/1D.svg`) into your web browser. You'll get a "file not found" page. So then just keep messing with that link until you get the file you want. Remember that file names are case-sensitive, so there's a difference between `1D.svg` and `1d.svg`.

**Comment by RobertAKARobin** [comment]
Alternatively, you can try this:

`cd` into your `project1` directory. Then:

``` sh
ls cards-svg/1D.svg
```

If it works, it'll print out the name of the file. If it doesn't work, it'll say `No such file or directory`. Keep trying different paths until you get the right one.

**Comment by amaseda** [comment]
@onesick Going to close this for now but feel free to re-open this issue if you have any more questions about this. Thx!
