### ISSUE TITLE
input value uppercase/lowercase

### ISSUE THREAD

**Issue by alifrumin** [ga-dc/project1#201]
I made a quiz and it works but you have to enter the answer exactly I have it... (all lowercase)... I know you can set it up to text transform the input value to uppercase and then test against uppercase so that if per say the user entered the answer in camelcase it would still work... is there an easier way in jquery?

Hope you are having a good day so far!

**Comment by RobertAKARobin** [comment]
Hm. You know, I'm not sure whether `text-transform` _actually_ makes it lowercase, or just makes it _look_ lowercase. My guess would be the latter.

Fortunately, Javascript has a `toLowercase` method!

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase

**Comment by alifrumin** [comment]
awesome Thank you!
