### ISSUE TITLE
Git issue

### ISSUE THREAD

**Issue by mcgrodsky** [ga-dc/project1#202]
Broke my program on master branch. Trying to access my most recent commit (which is live on my github page) and pull it down to start from that stage of my project.

**Comment by RobertAKARobin** [comment]
Can you be more specific with what you're encountering? Are you getting an error?

**Comment by mcgrodsky** [comment]
No error messages -changes to my CSS/Index broke my program. I had to stage and commit (but not push) these changes in order to access detached HEAD state. Tried to view most recent commit as a local file, but it was a very old version. Can't access most recent commit.

**Comment by RobertAKARobin** [comment]
Huh. OK, I'll be over in a mo'.

**Comment by mcgrodsky** [comment]
thank you! im at the long tables

**Comment by amaseda** [comment]
@mcgrodsky Guessing @RobertAKARobin took care of this but if you have any more problems with this just re-open the issue. Thx!
