### ISSUE TITLE
Non-standard fonts

### ISSUE THREAD

**Issue by MarkhamShofner** [ga-dc/project1#204]
I'm trying to bring a specific (non-inherent, and also not in google fonts) font into my page. How can I access this font, both on my computer, and on user's computer's, who won't have downloaded this specific font? Googling hasn't been particularly helpful.

**Comment by mattscilipoti** [comment]
Where are you getting the font from?  The source usually has instructions for utilizing in your page.

**Comment by mattscilipoti** [comment]
I recommend using a trusted, reliable source, with instructions.  Especially since there is little time left.
