### ISSUE TITLE
git hole

### ISSUE THREAD

**Issue by ArmaniH** [ga-dc/project1#205]
I think I'm in got hole. I've been pushing to gh-pages, but nothing outside of my initial commit of the README is in there. git log is showing that nothing has been committied since Sunday.

**Comment by RobertAKARobin** [comment]
What message do you get when you `git push`?

**Comment by ArmaniH** [comment]
Everything is up to date

**Comment by RobertAKARobin** [comment]
OK. What do you get when you do `git remote -v`?

**Comment by ArmaniH** [comment]
![screen shot 2015-10-28 at 12 01 26 pm](https://cloud.githubusercontent.com/assets/13981641/10794525/afe97cba-7d6b-11e5-8cb0-10706ef2866b.png)

**Comment by RobertAKARobin** [comment]
bv
