### ISSUE TITLE
issue with github

### ISSUE THREAD

**Issue by tkentor** [ga-dc/project1#207]
My changes are no longer committing to github. I changed the name of the folder, but now it won't let me add new changes even after changing the name back.

**Comment by ebirving** [comment]
What message do you get when you `git push`?
And what happens when you do `git remote -v`?

**Comment by tkentor** [comment]
Nothing happens with git remote -v.
Git push yields:
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by ebirving** [comment]
It looks like you lost the connection to your remote. Try doing a `git remote add origin` with your github repo and then try again.
