### ISSUE TITLE
Project 1

### ISSUE THREAD

**Issue by MaxKaye** [ga-dc/project1#214]
Is there any way that I can create a set of pinyin and english without having to create new functions?
How do I get it to flip back and forth without having to refresh the page? 
when I  click translation to English, Chinese character still remains. How do I get it so that “Chinese Character” switches to “English Text”?

My Chinese characters show up as illegal token when I call an array. Anyway to fix this?

**Comment by RobertAKARobin** [comment]
Are you using Chrome's built-in translator?

**Comment by MaxKaye** [comment]
no- Using mac's translator to get the words

**Comment by RobertAKARobin** [comment]
This sounds like it may be a Mac-specific issue, although I'm unsure. Would you mind going to the Genius Bar?

**Comment by MaxKaye** [comment]
code here: github.com/MaxKaye/project1

and for the last question I am trying to log the chinese here is what I have:

function logCharacters(chinese, english, pinyin) {
  console.log('a[' + english + '] = ' + chinese);
}
[你好，早上好，吃饭].forEach(logCharacters);

**Comment by MaxKaye** [comment]
yes i will

**Comment by amaseda** [comment]
@MaxKaye Made some good headway here. Feel free to re-open this issue if you have any additional questions.

**Comment by MaxKaye** [comment]
@amaseda thank you! got the refresh function running!
