### ISSUE TITLE
jQuery question

### ISSUE THREAD

**Issue by LaFrish** [ga-dc/project1#217]
If I am using jQuery, I have to put in the reference script source code in the head but I also have the script source code for script.js in the head. 

Do I use both references or do I have to combine them somehow? Please advise.

**Comment by joe-gz** [comment]
you can reference both! just make sure to include the jquery script first if you're then including jquery code in the other script

**Comment by joe-gz** [comment]
@LaFrish can you close this issue if you're all good?
