### ISSUE TITLE
Issue adding audio

### ISSUE THREAD

**Issue by MaxKaye** [ga-dc/project1#223]
I am trying to add audio files so user can hear pronunciation of the word. I have tried the following things and haven't gotten to work yet:

inline to html: 

``` html
<audio id="ni" src="niaudio.mp3" type="mpeg"></audio>
<div>
  <button onclick="document.getElementById('ni').play()">Play the Audio</button>
  <button onclick="document.getElementById('ni').volume+=0.1">Increase Volume</button>
  <button onclick="document.getElementById('ni').volume-=0.1">Decrease Volume</button>
</div>
```

and also added getElementByID. Any suggestions?

**Comment by RobertAKARobin** [comment]
Make sure you do your backtics on a new line by themselves.

Try changing the `type` to `audio/mpeg`.

http://www.w3schools.com/tags/tag_audio.asp#table2

**Comment by MaxKaye** [comment]
Thank you, I tried but still doesn't function
`<audio controls>
  <source src ="niaudio.mp3" type ="audio/mpeg">
  </audio>`

**Comment by RobertAKARobin** [comment]
You changed other aspects of your HTML. Leave it the way it was and change just one thing at a time. Then, once you get it working, change the HTML to be as you want it. Otherwise there are too many things going on to tell what the problem is.

**Comment by RobertAKARobin** [comment]
Also, make sure you don't put spaces around the `=` in HTML attributes.

For example, this is fine:

``` html
<div class="hello"></div>
```

This could cause errors:

``` html
<div class = "hello"></div>
```

**Comment by MaxKaye** [comment]
Noted. here were the first two changes you suggested- is this accurate?

```
<audio id="ni" src="niaudio.mp3" type="audio/mpeg">
<div>
  <button onclick="document.getElementById('ni').play()">Play the Audio</button>
  <button onclick="document.getElementById('ni').volume+=0.1">Increase Volume</button>
  <button onclick="document.getElementById('ni').volume-=0.1">Decrease Volume</button>
</div>
</audio>
```

**Comment by RobertAKARobin** [comment]
Almost. `<div>` shouldn't go inside `<audio>`. The only thing allowed inside is `<source>`.

**Comment by RobertAKARobin** [comment]
If it's still not working, can you confirm whether the file plays when you load it in iTunes and/or Quicktime?

**Comment by MaxKaye** [comment]
still not working- and yes the mp3 files work when I play in ITunes

**Comment by MaxKaye** [comment]
Here is what it looks like rn: 
<img width="415" alt="screen shot 2016-02-23 at 1 38 34 pm" src="https://cloud.githubusercontent.com/assets/9753582/13262437/d0a9fc08-da32-11e5-9fb0-fb1e28bba369.png">

**Comment by RobertAKARobin** [comment]
Hm. Well, the crossed-out speaker means it's not loading the audio at all. I'll come take a look.

**Comment by MaxKaye** [comment]
Thank you!
