### ISSUE TITLE
Selecting the correct button

### ISSUE THREAD

**Issue by tvcrawley** [ga-dc/project1#229]
I'm trying to increment var yes when the "correct" button is chosen.

I have it so that it increments when one of the three possible buttons is clicked but I can't seem to get the conditional right for the if statement so yes goes up only when the correct button is pushed. 

I tried using an if statement but have struck out on how to compare the clicked value to the correct value (rightAnswer).

I expected the counter to increment when I press correct.

The counter goes up when any of the three buttons are clicked.

My repo link is 
https://github.com/Chibiania/game-lab/blob/master/script.js 
and my question is about lines 85 which goes to 153-161.

**Comment by RobertAKARobin** [comment]
One way would be to use custom attributes. I talked about that in another issue:

https://github.com/ga-wdi-exercises/project1/issues/215

That is: you could store whether an answer is "right" or "wrong" in the HTML itself.

**Comment by tvcrawley** [comment]
I assigned the data attribute to the correct and incorrect answers.

I tried an if/else statement to compare the dataset to its value (either correct or incorrect).

When the correct answer is chosen, I expected the counter to increment and display in the console. 
When an incorrect answer is chosen, I expected the wrong answer string to print to the console.

What actually happens is the counter goes up now matter which answer is chosen.

Repo link: https://github.com/Chibiania/game-lab/blob/master/script.js
Lines:  setting data attribute: 92, 99, 107; if/else: 156-166

**Comment by RobertAKARobin** [comment]
I suspect `this.querySelector(".correct")` is returning the wrong button. `.querySelector` is searching the _entire_ `$(buttonSection)` for anything with the class of `correct`, and it's returning whatever happens to be the first one. How can you make sure it specifically gets the button you want?

**Comment by tvcrawley** [comment]
I've got it thanks to the geniuses!

**Comment by RobertAKARobin** [comment]
Yesss
