### ISSUE TITLE
Yun - no error, just doesn't work.

### ISSUE THREAD

**Issue by hh747hh** [ga-dc/project1#232]
I added the toggle function to have two sides on the memory card. It doesn't creates an error nor works...

any idea?

https://github.com/hh747hh/project_memory_card

**Comment by beckybeauchamp1** [comment]
Hi Yun! 

I took a quick look at your code. The`.toggle method` is actually a jQuery method and not available just using Vanilla JS. Here is the documentation: http://api.jquery.com/toggle/. Could you think of another way to achieve a similar effect using Vanilla JS? 

For example, maybe using `this.style.display = "inline"` and `this.style.display = "none"`

Also, I took a look at your CSS and there are some errors I found. For example, I would take a look at the following and see if you could identify the error: 

```
body { text-align: center;
       font-family: italic;

.cardImage {
  width: 100px;
  height : 100px;
  background-color: coral;
  color : white;
  }

```
