### ISSUE TITLE
Break line in string

### ISSUE THREAD

**Issue by tvcrawley** [ga-dc/project1#233]
Hi! 

So I tried using \n, break line command, backslash, and concat.
I also went to Joe for help and he couldn't figure it out either.

I expected the text beginning with \" to be displayed on the next line.

This happens: 
- \n: gives a space
- break line command: either does nothing and makes the desired text overflow to the next line OR it does its intended function while also printing itself to the screen
- backslash: does nothing
- concat: in combination with the above either does nothing, breaks the code, or does something that was outlined above

The link to my repo is 
https://github.com/Chibiania/game-lab/blob/master/script.js
my question is about line 4.

**Comment by jshawl** [comment]
what if you replace `textContent` with `innerHTML` https://github.com/Chibiania/game-lab/blob/168741baeec88ebb25bd1d350be8b66382808f3a/script.js#L78

**Comment by RobertAKARobin** [comment]
Try `\\n`.

What's going on here is Javascript is trying to "escape" the characters -- for example, turn `<` into `&lt;`.

**Comment by tvcrawley** [comment]
- "&lt;br /&gt;"  ---> switched to the default br line 
- \n ---> same result as \n (only gives me a space)

*I changed textcontent to innerhtml but there is no difference

**Comment by tvcrawley** [comment]
Just got help from Matt.

The answer was +"<br />"+ with the innerhtml
