### ISSUE TITLE
issue with __CSS__

### ISSUE THREAD

**Issue by LOHankins** [ga-dc/project1#246]
I tried creating divs and checkboxes inside other divs_____. I expected them to stay within their containers and to have their full expected shape_____ to happen._No matter what i seem to do some refuse to stay within their containers and exhibit really irritating size such as 0px by 0px.____ happened instead.
My repo link is _https://github.com/LOHankins/Project-1.git__ and my question is about lines 16 throuogh 66

___.

**Comment by tylercrosse** [comment]
Hey Louis, sorry for the delay in addressing this. Once you submit an issue feel free to come grab one of us, we've been a little short handed not having Adam around. I saw that you were able to fix this issue on your own which is great! :+1:
