### ISSUE TITLE
issue with game functionality

### ISSUE THREAD

**Issue by lknapalolo** [ga-dc/project1#247]
I tried if/else conditionals with various conditions (targeting the clickCounter/ lastClicked array), variables and placement(inside functions); for loops and finally just hard coding all the divs.... I expected the divs to either match (in which case nothing would happen- the squares would remain as is following the "click event") or fail to match (adding back the class 'cover' to the divs).

Either nothing happened or it broke my existing code (wouldn't remove the div 'class' at the click event) happened instead. As it stands now, I'm not getting any errors but the functionality isn't working as intended.

My repo link is https://github.com/lknapalolo/lauren-project1 and my question is about lines 54-83.

**Comment by andrewsunglaekim** [comment]
looking now, sorry!
