### ISSUE TITLE
Jesse, I saw that you use live reload...

### ISSUE THREAD

**Issue by ghost** [ga-dc/project1#25]
I've tried to implement it in the past, but haven't been able to get it working properly, is there any way you could help me set that up?

**Comment by jshawl** [comment]
sure! what did you try? what happened? what were you expecting? http://download.livereload.com/LiveReload-2.3.66.zip

**Comment by ghost** [comment]
I got it to work! Thanks!

**Comment by jshawl** [comment]
:+1:
