### ISSUE TITLE
CSS issue

### ISSUE THREAD

**Issue by superbuggy** [ga-dc/project1#251]
I'm trying to get a div to stay a fixed height and automatically scroll to the bottom when there is overflow without much success.

**Comment by andrewsunglaekim** [comment]
i asked jesse, another instructor about this. He whipped up this codepen for you http://codepen.io/jshawl/pen/JXygXL .

**Comment by andrewsunglaekim** [comment]
i don't know about a scroll bar though, unless u did some kind of iframe

**Comment by superbuggy** [comment]
thanks Andy!
