### ISSUE TITLE
issue with function

### ISSUE THREAD

**Issue by griffind2009** [ga-dc/project1#266]
I tried to create a function that would save a "word" and create blank spaces for the length of the word. This is as far as I got.

``` js
var word = function () {
  for (i=0; i<word.length; i++) {
    document.querySelector('input').innerHTML = "text"
  }
}
function myGuess () {
  for (i = 0; i < alphabet.length; i++) {
    var guesses = alphabet[i];
    if (alphabet[i] === true) {
      console.log[i] }

      else { canvasArray(); }
    }
  }
```

My repo link is https://github.com/griffind2009/Hangman_Project1

**Comment by nolds9** [comment]
Hey @griffind2009 I think there's some code here that might not be relevant to the problem at hand, what about a function that takes a `word` as an argument and returns a string with a blank space for each letter in that word.

**Comment by nolds9** [comment]
What I would recommend is focus on breaking down your game into steps. Before we worry about the DOM, maybe focus on just taking a word, and converting it to underscores.

**Comment by griffind2009** [comment]
I did some research on that but couldn't find the solution I was looking for. I saw &nbsp; but I don't think that would work in this case.  Do you know of some other possible solutions?

**Comment by jshawl** [comment]
what about something like this:

``` js
function convertLettersToUnderscores(word){
 var underscores = ''
  for(var i = 0; i < word.length; i++){
   underscores += "_"
  }
  return underscores
}
console.log(convertLettersToUnderscores("awesome!"))
```

**Comment by griffind2009** [comment]
That works, thanks! But I think I am missing a variable to create the underscores in the browser. I'm not sure if my question makes sense.

**Comment by jshawl** [comment]
What makes you think that?

**Comment by griffind2009** [comment]
I typed in a word and the spaces did not show in the browser, but with console.log they do show in the console.

**Comment by jshawl** [comment]
ok excelletn - so you want to update html - can you select the HTML element and use the `.html()` method?

**Comment by griffind2009** [comment]
would this be the correct format   var getWord = $(".word").html(); ?

**Comment by jshawl** [comment]
yes!

``` js
$(".word").html("this will be the new html for the thing with the word class :) ");
```

**Comment by nolds9** [comment]
It's been awhile so I'm going to close, feel free to reopen or a create a new issue if the problem persists...
