### ISSUE TITLE
Simon Game

### ISSUE THREAD

**Issue by khoitle** [ga-dc/project1#267]
Hey, I'm trying to figure out how to store a button value, and if it equals the sequence index, it'll continue the game. If not, then it'll just prompt "Try again."

Here is my code.

``` js
function newRound() {
  var sequence = [1, 2, 1]
  animate(sequence);
  var userClick = $("button").val();
  $("button").click(function(){
     var userClick = $("button").val();
     var userClickInput = userClick.value
     console.log(userClickInput);
  })
  if (userClickInput === sequence){
     alert("Yay")
   }
   else {
     alert("Try Again!")
   }
}
```

**Comment by nolds9** [comment]
One thing that might be helpful is to have the eventListener, outside the function. Or to pass a reference to your function, as the second argument to the event listener...

i.e: 

``` js
function newRound() {

}

$("button").on("click", newRound)
```

**Comment by nolds9** [comment]
also, I don't think a `button` can have a value, maybe you want to grab the `input`'s value...

**Comment by khoitle** [comment]
I'm not sure how to do that. <div class="mainBoard">

I got the JS to work, but when i click the button it goes straight to the else statement. I think i need to change the IF condition

Here's my html

<div class="mainBoard">
              <button class="red" data-tile="1" input = "1"></button>
              <button class="blue" data-tile="2" input= "2"></button>
              <button class="yellow" data-tile="3" input= "3"></button>
              <button class="green" data-tile="4" input= "4"></button>
      </div>

**Comment by KhoiLe89** [comment]
<div class="mainBoard">
              <button class="red" data-tile="1" input = "1"></button>
              <button class="blue" data-tile="2" input= "2"></button>
              <button class="yellow" data-tile="3" input= "3"></button>
              <button class="green" data-tile="4" input= "4"></button>
      </div>

**Comment by khoitle** [comment]
<div class="mainBoard">
              <button class="red" data-tile="1" input = "1"></button>
              <button class="blue" data-tile="2" input= "2"></button>
              <button class="yellow" data-tile="3" input= "3"></button>
              <button class="green" data-tile="4" input= "4"></button>
      </div>

**Comment by nolds9** [comment]
hey @KhoiLe89 looks like the `html` did not come through.... mind posting again

**Comment by KhoiLe89** [comment]
div class="mainBoard">
              <button class="red" data-tile="1" value = "1"></button>
              <button class="blue" data-tile="2" value= "2"></button>
              <button class="yellow" data-tile="3" value= "3"></button>
              <button class="green" data-tile="4" value= "4"></button>
      </div>

**Comment by KhoiLe89** [comment]
<body>
      <div class="mainBoard">
              <button class="red" data-tile="1" value = "1"></button>
              <button class="blue" data-tile="2" value= "2"></button>
              <button class="yellow" data-tile="3" value= "3"></button>
              <button class="green" data-tile="4" value= "4"></button>
      </div>

**Comment by KhoiLe89** [comment]
<body>
      <div class="mainBoard">
              <button class="red" data-tile="1" value = "1"></button>
              <button class="blue" data-tile="2" value= "2"></button>
              <button class="yellow" data-tile="3" value= "3"></button>
              <button class="green" data-tile="4" value= "4"></button>
      </div>

<body>
      <div class="mainBoard">
              <button class="red" data-tile="1" value = "1"></button>
              <button class="blue" data-tile="2" value= "2"></button>
              <button class="yellow" data-tile="3" value= "3"></button>
              <button class="green" data-tile="4" value= "4"></button>
      </div>

-

**Comment by khoitle** [comment]
html posted on slack. its not showing up in here for some reason.

**Comment by jshawl** [comment]
@KhoiLe89 how are you doing on this issue? any progress?

**Comment by nolds9** [comment]
going to go ahead and close this since we talked yesterday about this, feel free to reopen if issue persists
