### ISSUE TITLE
Blackjack - changing cards based on javascript randomised array

### ISSUE THREAD

**Issue by isabellabrookes** [ga-dc/project1#27]
Before I even start, so I set up nicely and don't have to go back half way through and hate life:

I assume that when I randomise the cards dealt via javascript, that I can manipulate the DOM and add classes to the card `<div>` in my HTML, which specify card number and card suit "dealt". 
This will in turn affect the styling properties that are already defined in CSS. 
   i.e.: classes for: A, 2, 3, 4, 5, 6, 7, 8, 9, 10, J, Q, K 
   and then classes for: hearts, diamonds, spades, clubs.

Am I on the right track?

**Comment by adambray** [comment]
Hey Isabella,

That sounds like it should work. One thought, instead of using classes on the divs (or in addition to), you may want to use JS to modify the HTML/Text content of the divs.

-Adam

**Comment by jshawl** [comment]
:+1: using classes to manipulate styles of dealt vs undealt sounds right. closing for now but please reopen if you'd like more feedback
