### ISSUE TITLE
issue with "validation error"(adrienne)

### ISSUE THREAD

**Issue by adriennedao** [ga-dc/project1#274]
I tried fixed the error "validation failed, user does not exist" I have checked on resources and checked the models relationship. Functionality of CRUD was working earlier, after having added the user, and session, it created the error. Unable to add. Error appeared .
 I expected _____ to happen._____ happened instead.
My repo link is ___ and my question is about lines ___.

**Comment by jshawl** [comment]
can I see the create action from RecipesController ?

**Comment by adriennedao** [comment]
``` rb
class RecipesController < ApplicationController

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def index
    @recipes = Recipe.all
  end

  def create
    @recipe = Recipe.create!(recipe_params)
    redirect_to @recipe
end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(recipe_params)
    redirect_to recipe_path(@recipe)
  end

def edit
  @recipe = Recipe.find(params[:id])
end

def destroy
  @recipe = Recipe.find(params[:id])
  @recipe.destroy
  redirect_to recipes_path
end

private

def recipe_params
  params.require(:recipe).permit(:name, :img_url)
  end
end
```

**Comment by jshawl** [comment]
In your create method, try adding the current user:

``` rb
def create
    @recipe = Recipe.create!(recipe_params.merge(user: @current_user))
    redirect_to @recipe
end
```

**Comment by adriennedao** [comment]
Thank you Jesse! Though it is still unresolved!  More error "can't write unknown attribute `user_id`"

**Comment by jshawl** [comment]
ok great! this is saying that a recipe does not belong to a user. Do you have a migration that adds a user_id to recipes table? if not you can create one:

```
$ rails g migration add_users_to_recipes user:references
```

**Comment by adriennedao** [comment]
Migrations are pending , should I run this: run: bin/rails db:migrate RAILS_ENV=development

**Comment by jshawl** [comment]
yes!

**Comment by adriennedao** [comment]
It resolved, thanks again!

**Comment by jshawl** [comment]
excellent! feel free to open another issue!
