### ISSUE TITLE
Unresolved issue 

### ISSUE THREAD

**Issue by adriennedao** [ga-dc/project1#275]
To Jesse: still unable to create the new recipe after having updated info on the def method. Error appeared again as "can't write unknown attribute `user_id`".

**Comment by jshawl** [comment]
what is the contents of `db/schema.rb`?

**Comment by adriennedao** [comment]
create_table "recipes", force: :cascade do |t|
    t.string   "name"
    t.string   "img_url"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer  "user_id"
    t.index ["user_id"], name: "index_recipes_on_user_id", using: :btree
  end

**Comment by jshawl** [comment]
hmm that looks right. and can i see recipes controller create action?

**Comment by adriennedao** [comment]
create_table "users", force: :cascade do |t|
    t.string "username"
    t.string "password"
  end

  add_foreign_key "ingredients", "recipes"
  add_foreign_key "recipes", "users"
end

**Comment by adriennedao** [comment]
def create
    @recipe = Recipe.create!(recipe_params.merge(user: @current_user))
    redirect_to @recipe
en

**Comment by jshawl** [comment]
hmm maybe try stopping and restarting your rails server? everything looks right to me...

**Comment by adriennedao** [comment]
Still not working. Restarted the server.

**Comment by jshawl** [comment]
ok let's try to narrow this down to either a database issue or a controller issue.

in db/seeds.rb can you add:

```
Recipe.create!(name:'my recipe', user: User.last)
```

and try seeding - any errors?
