### ISSUE TITLE
issue with creating a JS game wheel

### ISSUE THREAD

**Issue by nrc0004** [ga-dc/project1#279]
I tried I found a JS library that is supposed to help with the creation of a wheel (http://dougtesting.net/). After downloading and linking the library, I am unable to get the object to render like it says its supposed to after step 1. ( I can get the initial js wheel to happen, but when I try and customize it, it disappears.) 

Here is the link to my repo https://github.com/nrc0004/Project01. @

**Comment by amaseda** [comment]
@nrc0004 I don't see any code relating to the library in your repo (in either the master or gh-pages branch). Have you pushed it?

**Comment by nrc0004** [comment]
I think so. I saved it in the gh-pages branch when I pushed it, though. Does that help?

**Comment by amaseda** [comment]
There is some code on your gh-pages branch but I don't see anything in `index.html` or `script.js` relating to the library.

https://github.com/nrc0004/Project01/blob/gh-pages/index.html
https://github.com/nrc0004/Project01/blob/gh-pages/script.js

Are you sure you're pushing up the right branch?

@nrc0004

**Comment by amaseda** [comment]
Let me know if you've made any progress / need additional help with this (or the revert issue you mentioned to me earlier).

@nrc0004

**Comment by amaseda** [comment]
Going to close this one for now, but please re-open if you have any questions / comments.

@nrc0004
