### ISSUE TITLE
issue with jQuery IF-ELSE

### ISSUE THREAD

**Issue by laburr27** [ga-dc/project1#280]
I tried:

```
var blueQ1=$('td[name="blueQ"]').attr("value");
//the value is "1"

var blueA1=$('button[name="bA1"]').attr("value"); 
//the value is "0"

$('button[name="bA1]"]').click(function(){
  if ("blueA1" == "blueQ1") {
    $("#blueFb").css("background-color", "green");
  } else {
    $("#blueFb").css("background-color", "red");
  }
```

I expected the background color to change to red.

The background color stayed the default (purple) instead.

My repo link is https://github.com/laburr27/trivial-pursuit

and my question is about lines 22 - 27 in script.js.

**Comment by amaseda** [comment]
@laburr27 You're comparing the strings "blueA1" and "blueQ1" -- not the variables -- inside of your if statement. Try removing the quotation marks.

**Comment by laburr27** [comment]
Trying this using IDs instead of the NAME attribute.  Got the first IF ELSE to work but now working on the second...

$("#bA1").click(function(){
  // $("#blueFb").css("background-color", "green");
  if ("blueA1" == "blueQ1") {
    $("#blueFb").css("background-color", "green");
  } else {
    $("#blueFb").css("background-color", "red");
  }
});

$("#bA2").click(function(){
  // $("#blueFb").css("background-color", "green");
  if ("blueA2" == "blueQ1") {
    $("#blueFb").css("background-color", "green");
  } else {
    $("#blueFb").css("background-color", "red");
  }
});

**Comment by laburr27** [comment]
That did it!

So confusing when you need to use the quotes (") and when you don't...

Thanks!

**Comment by amaseda** [comment]
:+1:

Just know that if you surround it with quotes, you are not getting back the value stored in the variable. You are literally getting back the letters/words you have inside the quotes.
