### ISSUE TITLE
GitHub pages are not deploying

### ISSUE THREAD

**Issue by ghost** [ga-dc/project1#281]
Here is my original repo: https://github.com/maikelnabil/Refugees-Quiz/commits/gh-pages
It should deploy to: https://maikelnabil.github.io/refugees-quiz/
In the setting page of this repo, it says that the site is already published at this link, featuring my gh-pages branch

I've searched online, and found other people having the same problem
- some said that the problem is because the name of the repo is case sensitive
- some said that the problem disappeared when they started another repo
So, I started a second repo here: https://github.com/maikelnabil/refugees
It should be published here: https://maikelnabil.github.io/refugees/
I copied the files I produced in the previous repo, to the new one. Still nothing appear on the second repo

I found this link of troubleshooting GitHub pages
https://help.github.com/articles/troubleshooting-github-pages-builds/
i don't know where to look at Jekyll errors.
One of the errors on this link was about links, so I deleted all links from my second repo. Still nothing changes.

Someone on stackoverflow suggested that I should make sure that PageHub Pages are enabled in my GitHub settings. I don't see this option in my setting.

So far, my only successfully deployed GitHub page is https://maikelnabil.github.io/
Anything after the last / doesn't work.

**Comment by amaseda** [comment]
So I just pushed your code to a new repo that I made to test this out, and it works fine. Some links...

- Deployed version: https://amaseda.github.io/test-repo/
- Repo: https://github.com/amaseda/test-repo

I'm not sure what the exact problem is, but it might have to do with the fact that you had changed the repo name.

My recommendation would be to create a new Project 1 repo and push your code to a `gh-pages` branch on there. You **do not** need to delete the original repo.

Let me know how that goes.

@maikelnabil

**Comment by ghost** [comment]
Actually, James has just found the problem. The main file should be index.html, not Index.html. It's case sensitive. In the repo you made, Adrian, the index file doesn't start with a capital letter. That's why it works. I edited my repo, and it's working now perfectly!

Thanks a lot for your help! It took me a couple of hours chasing my tail, but I've learned few things along the way. Thanks a lot for your time!

**Comment by amaseda** [comment]
Ah, nice! Glad you were able to solve the issue.
