### ISSUE TITLE
GIthub is not deploying

### ISSUE THREAD

**Issue by evalaidc** [ga-dc/project1#282]
github repo: https://github.com/evalaidc/TowerOfHanoi/tree/gh-pages

github link: https://evalaidc.github.io/TowerOfHanoi/

The issue is that when I try to push the it says everything is up to date, but still not pushing it to the webpage, but the files are in the github and the gh-pages appears in the dropdown for the options of branches.

**Comment by amaseda** [comment]
The issue might be that you have a folder in your repo's root directory. You need to have `index.html` in the repo's root directory. Otherwise, gh-pages doesn't know what to serve up.

@evalaidc

**Comment by superbuggy** [comment]
you're running `git push origin gh-pages`?
