### ISSUE TITLE
Help with project

### ISSUE THREAD

**Issue by malrese1** [ga-dc/project1#284]
Need help working on the Js

**Comment by superbuggy** [comment]
Hey, can you elaborate on what you need help with? Since, the issues system (used by a great deal professional developers) relies on sharing the following types of information:

```
I tried ___.
I expected ___ to happen, but ___ happened instead.
My repo link is ___ and my question is about lines ___.
```

Check out this for reference:
https://github.com/ga-dc/wdi14/blob/master/asking-for-help.md
