### ISSUE TITLE
issue with ____

### ISSUE THREAD

**Issue by AmlakBarkon** [ga-dc/project1#289]
I pick a topic Tower of Hanoi. i tried to create three different size disk and put them on top of each other in order. and i can move each one on click to the other position. i expected to select where to go but it wouldn't let me. instead when i click to the disk it automaticly jump to the next table and instead of sitting on the bottom, it stays up.

**Comment by AndyWhitley** [comment]
Hi Amlak, could you please post a code snippet here with the code that appends the `disk` to the new table. Please use the backticks ` ```js ` above and ` ``` ` below your code snippet to allow for Javascript syntax highlighting.
