### ISSUE TITLE
HTML Validator rejecting Google Font href due to '|' character

### ISSUE THREAD

**Issue by meagdoh** [ga-dc/project1#292]
![screen shot 2017-04-06 at 9 14 53 am](https://cloud.githubusercontent.com/assets/16547063/24755820/982a0cca-1aa9-11e7-99e6-e2eaa95695b4.png)

Is this okay?

**Comment by AndyWhitley** [comment]
I'm sure you have addressed this by now, but unless it is breaking your code, don't worry about the fact that the validator doesn't like the url, it is formatted correctly.
