### ISSUE TITLE
issue with _join table___(tagging)

### ISSUE THREAD

**Issue by dionadk** [ga-dc/project1#303]
I am using a join table to tag a tag name to a picture uploaded. Currently i can add a pic and create a tag name for the pic. but not getting how to tag the pic to the tag name created(join table - tagging is supposed to link the tag id and pic id.). So that i can see all the tag name created for that pic.

link to my github repo: https://github.com/dionadk/Wexels

**Comment by ghost** [comment]
I think you should start by working on your routes.
- We don't create routes for joint tables. We instead use `member do`.
- You shouldn't repeat `resources :pics` more than once.
If you fix your routes, then you just need to add a method to your pics controller, and add a url to the view.

Work on this for a while, and let me know if you need further support!

**Comment by dionadk** [comment]
Thanks Mike. Will work on it.
