### ISSUE TITLE
I need help with assigning a new src to an image within a for loop

### ISSUE THREAD

**Issue by puzzleboks** [ga-dc/project1#33]
I am trying to loop through an array of img elements ('card'), set an event listener on each, and change the image src to a url (contained within another array 'imgUrlArray'. 

``` js
var imgUrlArray = ["images/bolt.png", "images/bolt.png", "images/star.png", "images/star.png", "images/circle.png", "images/circle.png", "images/square.png", "images/square.png", "images/triangle.png", "images/triangle.png",];
  var card = document.getElementById('board').getElementsByTagName("img");
  //console.log(card);
  for (var i=0; i<card.length; i++) {
    card[i].addEventListener("click", function(){
      this.src = imgUrlArray[i];
    })
  }
```

When I test this it fails because 'this' is undefined. When I explicitly set the src (this.src = imgUrlArray[0]) it seems to work, but will only assign that one image of course. 

Lon

**Comment by jshawl** [comment]
what if you use `event.target` instead?

``` js
for (var i=0; i<card.length; i++) {
    card[i].addEventListener("click", function(event){
      event.target.src = imgUrlArray[i];
    })
  }
```

**Comment by jshawl** [comment]
solution is to subtract 1 from `card.length`. undefined happens when you `imgUrlArray[arrayLength]`

**Comment by jshawl** [comment]
here's an example of a way you could dry up your code: http://codepen.io/jshawl/pen/aOKvaq?editors=101
