### ISSUE TITLE
Jquery might not be loading?

### ISSUE THREAD

**Issue by Curtismn87** [ga-dc/project1#36]
https://github.com/Curtismn87/Concentration-Project-1-/blob/master/script.js#L2-L9 - javascript
https://github.com/Curtismn87/Concentration-Project-1-/blob/master/index.html#L64-L66 - HTML

I get this error when I load my website, "Uncaught ReferenceError: $ is not defined."

The button functions I created work however. I looked online and read that I need to have a reference to jquery in the HTML, which I do? Bottom of the page, above the link to my external javascript page.

**Comment by jshawl** [comment]
This line is causing your issue - https://github.com/Curtismn87/Concentration-Project-1-/blob/1d48328766561633e342c7e4f0c3f5f0e5106e8a/index.html#L11 

Please reopen if removing it doesnt fix!
