### ISSUE TITLE
Help, it's like Inception all up in here

### ISSUE THREAD

**Issue by kscoulter** [ga-dc/project1#44]
I'm doing a concentration game. I have an array of objects that represent my cards. I'm need to figure out how to sort through objects based on the value of a key and return the entire object. And all of that needs to happen within a context of a click event.

Help.

**Comment by kscoulter** [comment]
I can come find you, just let me know.

**Comment by andrewsunglaekim** [comment]
what have you tried so far? I would create a function that you pass in an array(in this case, of objects) and the function returns the object you want. There no reason the functionality should change when nested in a click event.

**Comment by kscoulter** [comment]
It's going to be easier if I showed someone what I have.

**Comment by jshawl** [comment]
can you please take a screenshot or link to some code?

**Comment by andrewsunglaekim** [comment]
ie something like this:

```
var findObject = function(arrayOfObjects){
  for(var i = 0; i < arrayOfObjects.length; i++){
    // some conditional logic trying to find the object based a keyvalue pair or something
}
}

```

**Comment by kscoulter** [comment]
https://github.com/kscoulter/kscoulter.github.io/tree/concentrations-game

**Comment by kscoulter** [comment]
So when I click on a <td> cell, I know the class of that cell. Then I want to use that class to find a matching object, and then access that object's image property so I can use .css() method to change the background image to that url

**Comment by kscoulter** [comment]
So I guess I'm on my own here.

**Comment by andrewsunglaekim** [comment]
sorry we were in a meeting!

**Comment by andrewsunglaekim** [comment]
so in the click event, i would then iterate through all the objects select the one you want with an if conditional, store it in a variable. Than use that variable to change the background image.

**Comment by kscoulter** [comment]
Ok, I think that makes sense, I think I was making it more complicated than it needed to be.

**Comment by andrewsunglaekim** [comment]
I'm going to go ahead and close your issue. Let me know if you have any problems with this solution!
