### ISSUE TITLE
css fail

### ISSUE THREAD

**Issue by jkoul** [ga-dc/project1#45]
Hello!

I'm trying to set up a blackjack game board in an appealing way, and the headers of the "dealer" and "player" areas are showing up at the bottom of their boxes. I can't figure out why.

Here's my CSS code for the areas:

 .game {
  vertical-align: top;
  text-align: center;
  position: relative;
  height: 220px;
  width: 927px;
  display: inline-flex;
}
Also, the action buttons don't seem to be responding to clicks as they should.
HTML:

<div class="gamebuttons">
<input type = "button" class="gamebuttons" id="deal" value="Deal"></input>
<input type = "button" class="gamebuttons" id="hit" value="Hit"></input>
<input type = "button" class="gamebuttons" id="stand" value="Stand"></input>
<input type = "button" class="gamebuttons" id="double" value="Double Down"></input>
</div>

CSS:
.gamebuttons {
  text-align: center;
  padding: 10px;
  margin: 15px;
  size: 10em;
}

Help!

**Comment by jshawl** [comment]
Can you use the inspector to narrow down your issue? 

![](https://dl.dropboxusercontent.com/s/cinrrhlwhnxkizs/css-debug.gif?dl=0)

I have a hunch the `display:inline-flex` is causing issues, but the inspector should help!

**Comment by jkoul** [comment]
Got it, thanks!!! I have many other issues, but at least this one is out of the way.
