### ISSUE TITLE
Chrome Console Challenges

### ISSUE THREAD

**Issue by karldonus** [ga-dc/project1#46]
https://github.com/karldonus/projectOneGeneralAssembly/blob/master/script.js#L65-L79

Context: 
More of a generic problem. I'm struggling with interacting with the Chrome Console. When I attempt to identify the current typeof an object e.g. els.chipDisplay in Chrome, it returns a referenceError. 

Tried:
I thought it may have been my syntax. However, inserting the exact same code directly into my js file runs perfectly fine. Also, I tried calling a simple function. When I call it, I'm given a referenceError just like with the object. I can continue to do this as a workaround, but it is terribly inefficient. None of my classmates have a similar issue.

Question: How do I change my settings of Google Chrome Console to avoid a referenceError?

**Comment by jshawl** [comment]
can you share a screenshot of the error? cloning down your project now to take a closer look

**Comment by jshawl** [comment]
I wonder if it's the space after typeof and your parentheses.

why not just `typeof els.chipDisplay`?

**Comment by jshawl** [comment]
You can also set a breakpoint in the console to play with variables:

![](https://dl.dropboxusercontent.com/s/wu1wbyqia2eod56/console-help.gif?dl=0)

**Comment by karldonus** [comment]
Hey Jesse,

Thanks for your speedy reply.

Here's a screenshot. I don't believe it is typo-related.

for example, when I replace "typeof...." in console.log checker function
with a simple "hello" and call it inside the .js, it runs.

However, when I call checker() in chrome console, it doesn't execute,
citing the referenceError.
