### ISSUE TITLE
Getting onclick event to display correct text size or image

### ISSUE THREAD

**Issue by pdoulatshahi** [ga-dc/project1#48]
I have added the text/image value randomly to each card as a div value.

When I click on the card, I want it to either display the text value if it's a word, or display the image if it's an image.

**Comment by pdoulatshahi** [comment]
```
function clickOnTile(tile,val){
    clickCounter++;
    tile.style.background = '#DDD';
        tile.innerHTML = val;
    if (clickCounter % 2 === 0) {
      if (foodVocab.indexOf(val) === foodImages.indexOf(val)){
        console.log("test")
      }
    }
}
```

This is what I have so far. The "val" is either the text I want or the image URL I want, depending on the card.

**Comment by amaseda** [comment]
What sort of error/result are you getting when you use this function?

**Comment by pdoulatshahi** [comment]
It will add the text or the image URL to the innerHTML of the tile.

**Comment by pdoulatshahi** [comment]
Still struggling with this. I have tried appending img children using jquery and javascript and it's not working.
