### ISSUE TITLE
I need help with input box after click

### ISSUE THREAD

**Issue by malissaromero** [ga-dc/project1#49]
Hello,

I am doing a trivia game jeopardy style. I am looking to put a input field in my cell box after the box has been clicked. 

I have tried to put an input in the html but that shows right away and i want to do it after the click. 

I have also tried submit() but that just shows a submit button. 

I have tried .replace with. 

I think that my I am googling the wrong thing. Can I have a better search than "input box after click jquery". 

my page untouched:
![screen shot 2015-07-13 at 11 25 30 am](https://cloud.githubusercontent.com/assets/11203264/8653394/25228684-2952-11e5-8bc5-78fad0c95e83.png)

when clicked the text changes to: 
![screen shot 2015-07-13 at 11 27 52 am](https://cloud.githubusercontent.com/assets/11203264/8653431/5bc039f2-2952-11e5-91ff-ffd80a161bc4.png)

Thank you in advance.

**Comment by andrewsunglaekim** [comment]
In your click event, you need to manipulate the DOM to change the innerHTML/innerText

**Comment by andrewsunglaekim** [comment]
something like:

```
$(someElement).on("click", function(){
  $(this).text("Some new content")
})
```

**Comment by malissaromero** [comment]
I'm sorry I should have sent my code as well. 

$("#first500").on("click", function(){
   $(this).text("What is Michael Scott's catchphrase?").fadeIn(2000);

right below is where i want the input so that the user can put an answer

**Comment by jshawl** [comment]
``` js
// create an input element
var input = $("<input>")
// add it after the question
$(this).after(input)
```

**Comment by mattscilipoti** [comment]
You could also have one common place, outside of the table, visible at all times, where the user enters the response for the active question.

**Comment by malissaromero** [comment]
I may have to do that because as soon as I code .val at the end of the input variable, the input box no longer shows but I need to get the information from that box. There is no error message and looking at my atm homework, the syntax is correct so I am not sure what is going on. 

   var input = $("<input>").val();
   $(this).append(input);

I am worried that your advise will not let me tie the answers to the questions. I find it simpler to just tie the answer to the question within the click event but am out of ideas. 

I have tried a JS validator but there doesn't seem to be anything wrong with the code.
