### ISSUE TITLE
help i need somebody

### ISSUE THREAD

**Issue by ghost** [ga-dc/project1#54]
I'm having trouble getting event listeners to work, and there's a tricky li'l CSS thing I can't seem to figure out.

**Comment by amaseda** [comment]
Could you include some more info on the problem? https://github.com/ga-dc/pbj-project1/blob/master/asking-for-help.md

**Comment by ghost** [comment]
@amaseda hahah sorry... i figured out my css issue. i'm doing flash cards. i've got six boxes displayed on the page, and i want to add event listeners so that when the user clicks each box, a different prompt appears asking the user to provide the answer to whatever the topic is. my jQ code so far is: 

```
$(document).ready(function() {
  alert("i'm workin'");
  (".box1").on("click", function() {
    location.reload();
  })
})
```

the initial alert is working, so i know jQ is linked properly. my code looks just like the examples i found online. the class name is the same as in the html. not sure what to do!

**Comment by andrewsunglaekim** [comment]
instead of `location.reload()` you would want to do some sort of DOM manipulation. IE. change the html or text

**Comment by ghost** [comment]
sorry, that was me just trying things out to see what would work. i originally had a prompt("some text") in its place, would that make a difference? @andrewsunglaekim

**Comment by jshawl** [comment]
yes! `location.reload()` will reload the page. try adding a `console.log()` to log that some box was clicked

**Comment by jshawl** [comment]
like

``` js
$(document).ready(function() {
  alert("i'm workin'");
  (".box1").on("click", function() {
    console.log("box 1 was clicked")
  })
})
```
