### ISSUE TITLE
Help Concentration Game Card Layout

### ISSUE THREAD

**Issue by pdavies88** [ga-dc/project1#57]
I am having some trouble spacing out my elements in CSS I have figured out how to get the cards to flip over to reveal the image on the back but I am struggling on laying out the images so that I can repeat this process for multiple cards. I tried inline-block but the images become stacked on each other because the images are positioned absolute in order to get the image on the backside to flip in the same spot as the image on the front.

**Comment by jshawl** [comment]
What if you add a container div for each flippable card? Then you can make the containers lay out the way you want, but keep the inner flippable parts position absolute, like - http://codepen.io/jshawl/pen/ZGRQRM
