### ISSUE TITLE
inserting text upon click

### ISSUE THREAD

**Issue by jkoul** [ga-dc/project1#61]
I'm testing out the functionality of creating card objects upon pressing the "deal" button, by simply putting some text where the cards will go.

Here's the HTML for the general area in question:

<div class = "board">
  <div class="game" id="dealer">
    <h3>Dealer</h3>
    <div id="dcards"></div>
  </div>
  <div class="game" id="player">
    <h3>Player</h3>
    <div id="pcards"></div>
  </div>
</div>

And the Javascript adding some text to the "dealer" section:
var dealcards = $("#deal").click(function (){
  $("#dcards").append("<p>CARD</p>");
})

Any ideas why it doesn't show up?

Thanks in advance!

**Comment by jshawl** [comment]
what is the value of `$("#dcards")` in the console?

**Comment by andrewsunglaekim** [comment]
Could you give us the raw html and raw JS? you can link code or provide code using backticks

``````
sample code is wrapped in (```)
``````

**Comment by jkoul** [comment]
hmmmmmm that did not work. unfortunately i have to head to a lunch meeting......will check back in at 1:30

**Comment by jshawl** [comment]
There are a couple issues going on here. Try `console.log`ing the element's html each time you click to see if text is being appended.
