### ISSUE TITLE
Question on object methods

### ISSUE THREAD

**Issue by aag6z** [ga-dc/project1#62]
I had the following piece of code in my js file: 

``` javascript
function playingCard (valueString, suite, suiteRep, color){

  this.calcValue = function (str) {
    calcValue(str);
  }

  this.valueString = valueString;
  this.value = this.calcValue(this.valueString);
  this.suite = suite;
  this.suiteRep = suiteRep;
  this.color = color;
}

function calcValue (str) {
  switch (str) {
    case "A":
      this.value = [1, 11];
      break;
    case "1":
      this.value = 1;
      break;
...
```

I had to move that calcValue function above the this.value = this.calcValue(...) call in order for it to work. Why doesn't hoisting work in this case? Is there a better way to do this? What's the proper way to declare object methods?

**Comment by jshawl** [comment]
only named functions are hoisted. can you remove `this.` from each `this.calcValue` call?

**Comment by aag6z** [comment]
Will it still belong to the object in that case?

**Comment by jshawl** [comment]
no. If you want this explicitly attached to an object, either assign the function before calling it (no hoisting), or use a constructor function:

``` js
var playingCard = function(){
  this.attribute = "something"
}
```

and add methods to the prototype

``` js
playingCard.prototype = {
  calcValue: function(){
    console.log("calculating")
  }
}

var card = new playingCard()
card.calcValue()
```

**Comment by jshawl** [comment]
http://repl.it/wmF

**Comment by aag6z** [comment]
Awesome! Thank you. How would you do it if you just wanted to have the object methods declared but then defined outside of the constructor. The examples we went over in class we assigned and defined the methods all within the constructor. For this example I'm calling them inside the constructor but what if I just said calcValue is a method that can be called on a playingCard object but from outside the constructor.

**Comment by aag6z** [comment]
``` javascript
this.calcValue = function(){ calcValue(str); }
```

would that work?

and then 

``` javascript
playingCard.prototype = {
  calcValue: function (str) {
//define function here
```

**Comment by jshawl** [comment]
like this? http://repl.it/wmF/1

**Comment by aag6z** [comment]
ooh ok! and it's still an object method right?

**Comment by aag6z** [comment]
ok that makes sense although i think i need to look up "prototype"

**Comment by aag6z** [comment]
I'll close this issue because I got my question answered. Thanks :)
