### ISSUE TITLE
CSS Rule

### ISSUE THREAD

**Issue by Ryan-321** [ga-dc/project1#63]
I have a onclick event to add a CSS Rule for Memory game to flip a card.  But if players want to flip card again, they can't b/c rule is already appended to Stylesheet.  is there a way to change this?  

Also, is it possible to time a rule, so it lasts for a set amount of time?

**Comment by jshawl** [comment]
try toggling classes instead of inline styles:

``` js
$(".flip-me").on("click", function(){
  $(this).toggleClass("flipped")
})
```

**Comment by jshawl** [comment]
and the timed version:

``` js
$(".flip-me").on("click", function(){
  $(this).toggleClass("flipped")
  var el = $(this)
  if(el.hasClass("flipped")){
    setTimeout(function(){
      el.removeClass("flipped")
    },2000)
  }
})
```

**Comment by Ryan-321** [comment]
Works!  thanks jesse

**Comment by jshawl** [comment]
:+1: excellent!
