### ISSUE TITLE
Having trouble pushing to array

### ISSUE THREAD

**Issue by pdoulatshahi** [ga-dc/project1#64]
var clickedTiles = [];

```
  clickedTiles.push(val);
```

Within my clickonTile function this:

```
  clickedTiles.push(val);
```

Gives me the error:

Uncaught TypeError: Cannot read property 'push' of undefinedclickOnTile @ script.js:42onclick @ index.html:15

**Comment by amaseda** [comment]
Can you copy/paste...
• `clickOnTile` code
• Code where you declare the `clickedTiles` array

Wondering if it's a scope issue because your function does not know that `clickedTiles` is an array.

**Comment by pdoulatshahi** [comment]
It was a scope issue. I think it's fixed now.

**Comment by amaseda** [comment]
NICE! Comment here if it pops up again.

**Comment by pdoulatshahi** [comment]
Still having issue with pushing my values to the array. Not sure if it's still scope related.

**Comment by pdoulatshahi** [comment]
```
  window.clickedTiles.push(val);
```

 Is doing nothing
