### ISSUE TITLE
This issue;

### ISSUE THREAD

**Issue by englep10** [ga-dc/project1#65]
I am having some trouble with understanding why within my function of start it is not allowing to me to access my information.
https://github.com/englep10/blackjack/blob/master/blackjack.js#L32

**Comment by jshawl** [comment]
which info are you trying to access? what is that thing's value? undefined? any error / screenshot would be helpful

**Comment by englep10** [comment]
I am able to access my values within my arrays that I have created but that is because they are outside of my function that I am trying to set up. The current issue, is that I am trying to create a 'start' function that will place the first two values in the User's array when the event is called. I am under the impression that it is a scope issue but I am just having trouble initializing the function or knowing that the function is happening
