### ISSUE TITLE
issue with event listeners 

### ISSUE THREAD

**Issue by chrislovett03** [ga-dc/project1#67]
I tried changing my variables and verifying that my jquery selector is working. I expected an event listener to be added to my element but instead I receive an error saying my AddEventListener is not a function. I've tried debugging. Here is the code:

![screen shot 2015-07-13 at 2 09 31 pm](https://cloud.githubusercontent.com/assets/12041606/8656965/d4ddaf48-2968-11e5-8431-4ec7db284e25.png)

**Comment by jshawl** [comment]
`addEventListener` is a DOM method, but `boxOne` is a jquery object.

either use `boxOne[0].addEventListener` or `boxOne.on('click'...)`

**Comment by chrislovett03** [comment]
thanks, Jesse!
