### ISSUE TITLE
Input value not working

### ISSUE THREAD

**Issue by malissaromero** [ga-dc/project1#72]
Hello,

My input value is not working and there isn't an error message. I also went to a JS validator and it does not seem to be error message there either. 

```
1 var input = $("<input>").val();
2    $(this).append(input);
```

This is what my code looks like. When I take the .val() at the end of line 1, the input box shows but I am not able to write text in the box. 

When I put the .val(); at the end of line 1, the input box completely disappears. 

Thank you for help.

**Comment by adambray** [comment]
Hey Malissa,

One thing to consider is when your JS is running... specifically, has the DOM fully loaded when that JS is running?

Have you tried using 

``` js
$(document).ready(function() { 
// code here
});
```

or putting your `<script src="...">` tag right above the closing `</body>` tag?

-Adam
