### ISSUE TITLE
issue with getting keydown event to work

### ISSUE THREAD

**Issue by adrianshep** [ga-dc/project1#78]
I tried running the keydown event handler as Andy showed us on Friday with hangman lab. I expected html content to appear as did happen when I tested it using a click handler. Nothing happened with the html and nothing showed up on the console.

**Comment by jshawl** [comment]
can you please share your code?

**Comment by adrianshep** [comment]
var statesCapitals = [
    [["Connecticut"], ["Hartford"]],
    [["New Jersey"], ["Trenton"]],
    [["New York"], ["Albany"]],
    [["Ohio"], ["Columbus"]],
    [["Pennsylvania"], ["Harrisburg"]],
  ]; 

$(".qBox").on("keydown", function(event){
      if (event.keyCode === 70) {
        $(".qBox").html("What is the state capital of " + statesCapitals[0][0] + " ?")
      }
    })

**Comment by jshawl** [comment]
also I recommend using `keyup` it's more reliable than `keydown` - https://jsfiddle.net/v0e2ot6m/

**Comment by jshawl** [comment]
yes im farily certian using `keyup` will work here

**Comment by adrianshep** [comment]
tried keyup with no luck, but i'm wondering if i'm misunderstanding the event function: does the key event have to happen in an input field to be read? in other words, just being on the html page won't do it?  thanks.

**Comment by jshawl** [comment]
solution was to use `textarea` instead of `div` so that `keyup` event fires
