### ISSUE TITLE
Consolidating key press and click listeners

### ISSUE THREAD

**Issue by robertbenjamin** [ga-dc/project1#80]
From: https://github.com/robertbenjamin/flashy-flash-card/blob/master/flashy.js#L76-L87

Is there anyway to consolidate two events to perform _one_ result when either of them is triggered? Specifically, a click on a specific object and a keypress of a specific key at any time (listening to the document). Right now, the only way of doing this would be the opposite of DRY:

``` javascript
$(".next_card").click(function() {
    i++;
    $(".question_text").html(cards[i].question);
});

$(document).keyup(function(e) {
    if (e.which === 39) {
        console.log("next card");
        i++;
        $(".question_text").html(cards[i].question);
    }
});
```

I've tried using a .on() function with both a "click" and "keyup" event inside of it, but have no idea how to structure the `if (e.which === keyboardCode) {}` section to continue to listen for a click.

**Comment by jshawl** [comment]
you have to have two listeners that call the same function - https://jsfiddle.net/mLzcrbLd/
