### ISSUE TITLE
didn't create my repo with Git Hub pages

### ISSUE THREAD

**Issue by M00staff** [ga-dc/project1#83]
I used a friend of mine's host instead.  I'm worried that if i change the repo name or create a new one, it will unlink it from my drive or lose my commit history.  What should i do?

**Comment by andrewsunglaekim** [comment]
I'm not entirely sure what you're referring to. But you can always just add another remote repository on your local repo, and push to a new repo on github

**Comment by M00staff** [comment]
OK makes sense, but we turned in our Git Hub repo URL as a part of the HW this weekend.  Will it be OK if i change project repos?

**Comment by M00staff** [comment]
it worked but i lost my commit history hope that's not an issue. 

https://github.com/M00staff/M00staff.github.io

**Comment by jshawl** [comment]
:+1: yes it is ok! there are ways to avoid this - by adding a new remote rather than intializing a new repository - but this works just as well
