### ISSUE TITLE
Issue with appending elements

### ISSUE THREAD

**Issue by nolds9** [ga-dc/project1#87]
I am working on creating a question and answer screen within my jeopardy game...
I have an event listener working to hide the gameboard, and have a basic function to show the question and multiple choices that I want, however I am having trouble with the formatting as I want each answer to be its own div with unique classes...
I tried making a for loop to apppend each choice to the parent container and also chain an addClass method, however I am not getting any result.

Currently have my multiple choice as an array.

**Comment by andrewsunglaekim** [comment]
can you post the JS that you have  currently that you want generating the answers in divs? Then can you post what you're getting instead, or not getting. In addition to any errors you might have gotten.
