### ISSUE TITLE
Removing img child from div

### ISSUE THREAD

**Issue by pdoulatshahi** [ga-dc/project1#88]
I have this 

```
    if ($("#"+tileIds[0]).find('img').length) {
```

This finds img in the tile id I've clicked on. How do I remove the img from the div?

<div id="tile_10" onclick="clickOnTile(this,'vocab/food/images/strawberry.png')" style="background: green;"><img src="vocab/food/images/strawberry.png"></div>

<img src="vocab/food/images/strawberry.png">

Also want to know how to make these changes gradual instead of immediate - i.e. on my 2nd click on the concentration game, it doesn't even show the word, it just displays it as blank right away.

**Comment by jshawl** [comment]
can you use `$("#"+tileIds[0]).find('img').remove()` ?
