### ISSUE TITLE
tying card values to deal result

### ISSUE THREAD

**Issue by jkoul** [ga-dc/project1#89]
I'm afraid I'm pretty stumped at the moment. I'm trying to set up the game (aka dealing four cards, with "card" values, in the right position) when I click the "deal" button of my game.

I've gotten a card to appear once "face down", but not two. It also is almost certainly not tied to the value of an actual card, which is clearly a crucial piece of the puzzle here.

If I get this worked out, I think I'll be in solid shape heading into tomorrow. But it's a big if at the moment. HELP!

**Comment by jshawl** [comment]
try breaking down your problem into something smaller.

when you "deal", what if you console.log each of the cards to make sure you're able to access the data?

once the console.log is workin as intended, then you can add to the page

**Comment by jshawl** [comment]
also, what does it mean for a card to be face down? is it an image src, or a class?
