### ISSUE TITLE
i need help with...for loop

### ISSUE THREAD

**Issue by rewarren** [ga-dc/project1#90]
trying to get my trivia questions to move on to the next.  the function below works - but only initially.  I'm confused about where to put my for loop and conditional statements. I've flip flopped between putting them within the function below  and then change it to after the closing }.  i can't get the function below to work unless my for and if statements are commented-out..   

```
function getRandomQuestion() {
  var random = Math.floor(Math.random() * triviaQuestions.length);
  console.log(random);
  triviaQuestions.eq(random).show();
}

getRandomQuestion();
```

**Comment by andrewsunglaekim** [comment]
its hard to say, theres alot being abstracted in the code your showing, could you provide a bit more context? I don't see any `for` or `if` statements. Can you show me what `triviaQuestions` is, additionally can you show where the `for` and `if` statements broke?
