### ISSUE TITLE
Help request -- variable issue

### ISSUE THREAD

**Issue by ghost** [ga-dc/project1#91]
I'm having issues referencing my variable in the second alert in the code below.
I thought that :
-I set var q1answer equal to the value of the line where the value q1correct was checked
-By doing so I'd be to reference the value of var q1answer in line 7 below.
-Instead, line 7 gives an alert indicating that q1answer is undefined.
-This seems odd to me because the code is correctly identifying whether the answer is right or wrong, so the reference to q1answer seems to be working in line 3. 

( "input[id='q1submit']" ).on( "click", function() {
  var q1answer = $("input[value='q1correct']:checked").val();
  if (q1answer) {
    alert("Correct!")
  }
  else {
    alert("Incorrect. The correct answer is " + q1answer + ".")
  }
})

**Comment by andrewsunglaekim** [comment]
Can you slap a `console.log()` right after your variable instantiation and see what the value is? I think because it is undefined its going to the else conditional.

Also make sure you wrap any code in triple backticks <pre>```</pre>

**Comment by ghost** [comment]
Hey Andy, do you mean console.log("q1answer")? Not sure if I understood correctly, but when I added console.log("q1answer");  on the line below where I define the variable, I got q1answer as the result in the console......

**Comment by ghost** [comment]
Hey, I am still struggling with the same variable issue. I've tried defining my variables lots of different ways and have been stuck on this issue for hours. Is anyone available to look at my code with me? Thanks.

**Comment by jshawl** [comment]
http://codepen.io/jshawl/pen/gpKGxX?
