### ISSUE TITLE
Need help with structuring listeners

### ISSUE THREAD

**Issue by petergcutler** [ga-dc/project1#92]
Hey, could use some help with managing my listeners...

I have an array of objects, each object contains three fields: 
    front-content
    back-content
    correctness

At page load, card 1 is displayed: its front, back and correctness.

On click, depending on the button, I want to either 
    assign the card a true/false value if it was answered correctly,
    or to switch cards and display the next value in the array.

I'm working through how to simultaneously: 
    persistently listen for clicks on either a correctness button or next card button
    make changes to the dom based on these inputs
    maintain position in the loop across the array index

I think I'm butting up against some issues with object-oriented setup. Would love some help thinking about it. I'm in the corner by rooms 17/18. Thanks a lot.

**Comment by andrewsunglaekim** [comment]
What have you tried that isn't working? What result are you getting instead?
