### ISSUE TITLE
Appending Elements

### ISSUE THREAD

**Issue by silviascript** [ga-dc/project1#93]
https://github.com/siltastic/trivia-game/blob/master/js/main.js

My Goal: In order to append my questions, choices, and answers, I needed to append them into my "trivia-container" div; which works, then append more items into that container. However, in my html, I have text like "[object Object],[object Object],[object Object]" throughout my containers.

``` html
<div class="column-right">
  <div class="trivia-container">
    [object Object],[object Object],[object Object]
    <h2></h2>
    <ul>
      <li>/<li>
      <li>/<li>
      <li>/<li>
    </ul>
  </div> <!-- Closes "trivia-container" -->

  <div class="trivia-container">
    [object Object],[object Object],[object Object]
    <h2></h2>
    <ul>
      <li>/<li>
      <li>/<li>
      <li>/<li>
    </ul>
  </div> <!-- Closes "trivia-container" -->
</div> <!-- Closes "column-right" -->
```

I've refactored my code from my previous version to see if there was an error.

**Comment by jshawl** [comment]
whenever you see `[object Object]` it means that you're trying to print a JS object to html. I imagine you want one of those object's attributes, like `myObject.question`

**Comment by jshawl** [comment]
check out this pen - http://codepen.io/jshawl/pen/rVKMGr?editors=101
