### ISSUE TITLE
Switching git branches

### ISSUE THREAD

**Issue by mosesadg** [ga-dc/project1#95]
Hi,
I am trying to switch to my project branch so that the project url renders the index.html file, but I am unable to.

I get this message when I try to swicth and commit. But the index.html file still doesnt render on the url site. I am unable to figure out what I am doing wrong. Thanks!

git commit -m"preseidential trivia"
On branch gh-pages
Your branch is up-to-date with 'origin/gh-pages'.
nothing to commit, working directory clean

**Comment by andrewsunglaekim** [comment]
you have to do `git push origin gh-pages`

**Comment by jshawl** [comment]
closing for now - please reopen if you have another issue
