### ISSUE TITLE
CSS Issue w/ one card in particular

### ISSUE THREAD

**Issue by jeffjones89** [ga-dc/project1#97]
<img width="559" alt="screen shot 2015-07-14 at 9 04 27 am" src="https://cloud.githubusercontent.com/assets/11494386/8673791/658855ea-2a07-11e5-85ad-6096ee17c7ae.png">

The first card in the dealer div is not formatting correctly, and I cannot figure out why. All cards in both player/dealer div have the same CSS attributes, as do both divs. 

All cards are generated using jquery to assign a value and create divs within the appropriate playing area, but only the first card in the dealer div is giving me trouble.

```
.playerArea, .dealerArea {
    height: 200px;
    position: relative;
    width: 90%;
    background-color: #16BC16;
    border: 3px black solid;
    margin: 0 auto;
    margin-bottom: 5px;
}
```

```
.playerCard, .dealerCard, .hiddenCard {
  background-color: white;
  border-color: #808080 #000000 #000000 #808080;
  border-width: 1px;
  border-style: solid;
  color: #000000;
  font-size: 20pt;
  position: relative;
  width:  3.75em;
  height: 5.00em;
  text-align: center;
  line-height: 5;
  display: inline-block;
  margin-left: 5px;
  margin-top: 30px;
}
```

**Comment by jshawl** [comment]
Check out this http://codepen.io/jshawl/pen/BNVdWz

and also https://css-tricks.com/centering-css-complete-guide/
