### ISSUE TITLE
Appending td to a table

### ISSUE THREAD

**Issue by kscoulter** [ga-dc/project1#98]
I need to figure out how to append an array to my table in a way that would break it into multiple rows.
So far, I've only been able to do one row. Other methods produced weird results. Please help.

**Comment by andrewsunglaekim** [comment]
what have you tried? I would recommend a for loop

**Comment by jshawl** [comment]
here's an example - http://codepen.io/jshawl/pen/bdKrmR

**Comment by kscoulter** [comment]
https://github.com/kscoulter/kscoulter.github.io/tree/concentrations-game

I've tried adding a conditional to the for loop, if i is divisible by 3, add tr element. That didn't work. I'm not sure how to make sure the split is even.

**Comment by kscoulter** [comment]
Jesse, that did not work for me. I need multiple cells in a row. And I need the number of cells to be the same in each row. And I need the number of cells to be equal to my array length.
