### ISSUE TITLE
Not receognizing Input ID

### ISSUE THREAD

**Issue by malissaromero** [ga-dc/project1#99]
I am doing a trivia game. The code:  https://github.com/malissaromero/The-Office-Trivia-Game/blob/master/index.js

I created a input inside of my JS file because I need it to show after I click on a cell box on a table. I am tying the user's input to an answer. However, when I type an answer for a different question, the input only recognizes the first input variable even though it is not a global variable and not in its scope. Nick, helped me by adding an ID to each input but that is still not working. 

Here is what we did: 

```
var input = $("<input>");
input.attr("id=1.5")
$(this).after(input);

$("#1.5").keypress(function(e) {
if (event.which == 13) {
  event.preventDefault();
  var userInput = $("#1.5").val();
  if (userInput === "daffy duck") {
```

Thank you.

**Comment by malissaromero** [comment]
I also tried different syntax for .attr

`input.attr("id", "2.5")`

**Comment by amaseda** [comment]
Hi @malissaromero. Sorry, we were in a meeting - taking a look at this now!

**Comment by amaseda** [comment]
With `var input = $("<input>");` are you trying to target an existing input or create a new one? If it's the former, try removing the `< >` around `input`.

And make sure you use the `.attr` syntax that you mentioned in your second comment.

**Comment by malissaromero** [comment]
Adrian,

Thank you for responding, I am going crazy because I think I have to scrap
a big part of my code because this continues to not work.

Okay, I have a jeapardy style table where you click on "500" and then the
question with an input box (for the answer) shows up. I could not put the
input box in my html because i need it to show up after the click on "500".

So in this case, I can't remove the <> because it is creating a new input.
